-- ============================================================
-- 特征字典注册表种子补丁
--   qm_feature_category / qm_feature_definition
--   qm_feature_set_version / qm_feature_set_item
--
-- 数据来源：config/features/model_training_feature_catalog_v1.json
--   version=v2.0  features=534  sha256(LF 归一)=8bc5b3cd965ee34388df199ac0c2129ed8597a5c82362502df6008d6c2eb4930
--
-- 背景：管理后台「训练服务 → 特征字典」读取顺序为
--   1) QuantDB 因子目录（qm_training_factor_catalog_version, status=published）
--   2) 特征注册表（qm_feature_set_version, status=active）← 本补丁写入
--   3) config/features/model_training_feature_catalog_v1.json（文件回退）
--   DB 注册表为空时页面显示「来源: file」，且无法在 DB 侧统一管理。
--
-- 幂等性：全部 ON CONFLICT DO NOTHING，不覆盖 DB 已有行，可重复执行；
--   运维后续在 DB 里的改动不会被本补丁冲掉。
--
-- 自动执行：新部署/新库由 data/upgrade_v1.0.10.sql（本文件副本）随服务启动
--   幂等重放导入；本文件保留作为生成产物与手工执行入口。
--
-- 执行（存量库手工执行一次）：
--   docker exec -i quantmind-db psql -U quantmind -d quantmind \
--     < backend/shared/patches/qm_feature_registry_seed.sql
--
-- 注意：本文件由脚本从上述 JSON 生成，请勿手工编辑；数据变更请改 JSON 后
--   重新生成，并同步覆盖 data/upgrade_v1.0.10.sql。
-- ============================================================

BEGIN;

-- ---- 1. 分类（15 个）----
INSERT INTO qm_feature_category (category_id, category_name, sort_order, description) VALUES
    ('ohlcv', '基础行情', 1, NULL),
    ('momentum', '动量', 2, NULL),
    ('volatility', '波动率', 3, NULL),
    ('liquidity', '成交量与流动性', 4, NULL),
    ('fund_flow', '资金流', 5, NULL),
    ('style', '风格因子', 6, NULL),
    ('industry', '行业因子', 7, NULL),
    ('microstructure', '微观结构', 8, NULL),
    ('gtja', 'GTJA Alpha191 (价量因子)', 9, NULL),
    ('chip', '筹码分布', 8, NULL),
    ('concept', '概念热度', 9, NULL),
    ('technical', '技术指标', 10, NULL),
    ('fundamental', '基本面', 11, NULL),
    ('holding', '持仓结构', 14, 'CCASS/南向资金持仓结构因子（本地日频，markets:HK）'),
    ('custom', '自建因子', 12, NULL)
ON CONFLICT (category_id) DO NOTHING;

-- ---- 2. 版本（status=active，供后台优先读取）----
INSERT INTO qm_feature_set_version (version_id, version_name, status, feature_count, effective_at)
VALUES ('v2.0', 'QM Feature Set v2.1 (L2/microstructure unlocked, 20260820)', 'active', 534, NOW())
ON CONFLICT (version_id) DO NOTHING;

-- ---- 3. 特征定义（534 个）----
--   feature_id 留空：JSON 里的 feature_id 形如 feat_ohlcv_001，不是 UUID，
--   与 qm_feature_definition.feature_id（UUID 列）不兼容。
INSERT INTO qm_feature_definition
    (feature_key, feature_name, explanation, formula, category_id, source_table_fields) VALUES
    ('open', '开盘价（复权）', '', 'OpenPrice', 'ohlcv', '股票历史日行情信息表后复权'),
    ('high', '最高价（复权）', '', 'HighPrice', 'ohlcv', '股票历史日行情信息表后复权'),
    ('low', '最低价（复权）', '', 'LowPrice', 'ohlcv', '股票历史日行情信息表后复权'),
    ('close', '收盘价（复权）', '', 'ClosePrice', 'ohlcv', '股票历史日行情信息表后复权'),
    ('volume', '成交量', '', 'Volume', 'ohlcv', '股票历史日行情信息表后复权'),
    ('factor', '通用因子桶(待细分)', '', '', 'ohlcv', '6_ml_datasets/l1_l2_factors（A股L1+L2因子训练宽表）'),
    ('mom_ret_1d', '1日收益率动量', '', '(C_t/C_{t-1})-1', 'momentum', '股票历史日行情信息表后复权.ClosePrice'),
    ('mom_ret_3d', '3日收益率', '', '(C_t/C_{t-3})-1', 'momentum', '6_ml_datasets/l1_l2_factors（A股L1+L2因子训练宽表）'),
    ('mom_ret_5d', '5日收益率动量', '', '(C_t/C_{t-5})-1', 'momentum', '股票历史日行情信息表后复权.ClosePrice'),
    ('mom_ret_10d', '10日收益率', '', '(C_t/C_{t-10})-1', 'momentum', '6_ml_datasets/l1_l2_factors（A股L1+L2因子训练宽表）'),
    ('mom_ret_20d', '20日收益率动量', '', '(C_t/C_{t-20})-1', 'momentum', '股票历史日行情信息表后复权.ClosePrice'),
    ('mom_ret_60d', '60日收益率动量', '', '(C_t/C_{t-60})-1', 'momentum', '股票历史日行情信息表后复权.ClosePrice'),
    ('mom_ret_120d', '120日收益率', '', '(C_t/C_{t-120})-1', 'momentum', '6_ml_datasets/l1_l2_factors（A股L1+L2因子训练宽表）'),
    ('mom_ma_gap_5', '收盘价偏离5日均线', '', 'C_t/MA(C,5)-1', 'momentum', '股票历史日行情信息表后复权.ClosePrice'),
    ('mom_ma_gap_10', '收盘价偏离10日均线', '', '(C_t/MA(10))-1', 'momentum', '6_ml_datasets/l1_l2_factors（A股L1+L2因子训练宽表）'),
    ('mom_ma_gap_20', '收盘价偏离20日均线', '', 'C_t/MA(C,20)-1', 'momentum', '股票历史日行情信息表后复权.ClosePrice'),
    ('mom_ma_gap_60', '收盘价偏离60日均线', '', 'C_t/MA(C,60)-1', 'momentum', '股票历史日行情信息表后复权.ClosePrice'),
    ('mom_ma_gap_120', '收盘价偏离120日均线', '', '(C_t/MA(120))-1', 'momentum', '6_ml_datasets/l1_l2_factors（A股L1+L2因子训练宽表）'),
    ('mom_ema_gap_12', '动量 指数均线 偏离 12', '', '', 'momentum', '6_ml_datasets/l1_l2_factors（A股L1+L2因子训练宽表）'),
    ('mom_ema_gap_26', '动量 指数均线 偏离 26', '', '', 'momentum', '6_ml_datasets/l1_l2_factors（A股L1+L2因子训练宽表）'),
    ('mom_macd_dif', '动量 MACD DIF', '', '', 'momentum', '6_ml_datasets/l1_l2_factors（A股L1+L2因子训练宽表）'),
    ('mom_macd_dea', '动量 MACD DEA', '', '', 'momentum', '6_ml_datasets/l1_l2_factors（A股L1+L2因子训练宽表）'),
    ('mom_macd_hist', 'MACD柱值', '', '2*(DIF-DEA)', 'momentum', '股票历史日行情信息表后复权.ClosePrice'),
    ('mom_rsi_6', '6日 RSI 相对强弱指标', '', '', 'momentum', '6_ml_datasets/l1_l2_factors（A股L1+L2因子训练宽表）'),
    ('mom_rsi_14', 'RSI(14)', '', '100-100/(1+RS_14)', 'momentum', '股票历史日行情信息表后复权.ClosePrice'),
    ('mom_kdj_k', 'KDJ-K', '', 'SMA(RSV,3,1)', 'momentum', '股票历史日行情信息表后复权.HighPrice/LowPrice/ClosePrice'),
    ('mom_kdj_d', '动量 KDJ d', '', '', 'momentum', '6_ml_datasets/l1_l2_factors（A股L1+L2因子训练宽表）'),
    ('mom_kdj_j', '动量 KDJ j', '', '', 'momentum', '6_ml_datasets/l1_l2_factors（A股L1+L2因子训练宽表）'),
    ('mom_roc_12', '动量 roc 12', '', '', 'momentum', '6_ml_datasets/l1_l2_factors（A股L1+L2因子训练宽表）'),
    ('mom_breakout_20d', '20日突破强度', '', 'C_t/MAX(H,20)-1', 'momentum', '股票历史日行情信息表后复权.HighPrice/ClosePrice'),
    ('SUMP20', '过去20个交易日中收盘上涨的天数', '', 'Alpha158 rolling factor', 'momentum', 'feature_snapshots/model_features_*.parquet'),
    ('SUMN20', '过去20个交易日中收盘下跌的天数', '', 'Alpha158 rolling factor', 'momentum', 'feature_snapshots/model_features_*.parquet'),
    ('SUMD20', '过去20日上涨天数减下跌天数', '', 'Alpha158 rolling factor', 'momentum', 'feature_snapshots/model_features_*.parquet'),
    ('SUMP30', '过去30个交易日中收盘上涨的天数', '', 'Alpha158 rolling factor', 'momentum', 'feature_snapshots/model_features_*.parquet'),
    ('SUMN30', '过去30个交易日中收盘下跌的天数', '', 'Alpha158 rolling factor', 'momentum', 'feature_snapshots/model_features_*.parquet'),
    ('SUMD30', '过去30日上涨天数减下跌天数', '', 'Alpha158 rolling factor', 'momentum', 'feature_snapshots/model_features_*.parquet'),
    ('SUMP60', '过去60个交易日中收盘上涨的天数', '', 'Alpha158 rolling factor', 'momentum', 'feature_snapshots/model_features_*.parquet'),
    ('SUMN60', '过去60个交易日中收盘下跌的天数', '', 'Alpha158 rolling factor', 'momentum', 'feature_snapshots/model_features_*.parquet'),
    ('SUMD60', '过去60日上涨天数减下跌天数', '', 'Alpha158 rolling factor', 'momentum', 'feature_snapshots/model_features_*.parquet'),
    ('RANK5', '当前日收益在过去5日收益中的分位排名', '', 'Alpha158 rolling factor', 'momentum', 'feature_snapshots/model_features_*.parquet'),
    ('RANK10', '当前日收益在过去10日收益中的分位排名', '', 'Alpha158 rolling factor', 'momentum', 'feature_snapshots/model_features_*.parquet'),
    ('RANK20', '当前日收益在过去20日收益中的分位排名', '', 'Alpha158 rolling factor', 'momentum', 'feature_snapshots/model_features_*.parquet'),
    ('RANK30', '当前日收益在过去30日收益中的分位排名', '', 'Alpha158 rolling factor', 'momentum', 'feature_snapshots/model_features_*.parquet'),
    ('RANK60', '当前日收益在过去60日收益中的分位排名', '', 'Alpha158 rolling factor', 'momentum', 'feature_snapshots/model_features_*.parquet'),
    ('vol_std_5', '5日收益率标准差', '', '', 'volatility', '6_ml_datasets/l1_l2_factors（A股L1+L2因子训练宽表）'),
    ('vol_std_10', '10日收益率标准差', '', '', 'volatility', '6_ml_datasets/l1_l2_factors（A股L1+L2因子训练宽表）'),
    ('vol_std_20', '20日收益率标准差', '', 'STD(ret,20)', 'volatility', '股票历史日行情信息表后复权.ClosePrice'),
    ('vol_std_60', '60日收益率标准差', '', 'STD(ret,60)', 'volatility', '股票历史日行情信息表后复权.ClosePrice'),
    ('vol_atr_14', 'ATR(14)', '', 'MA(TR,14)', 'volatility', '股票历史日行情信息表后复权.HighPrice/LowPrice/ClosePrice'),
    ('vol_atr_20', '20日平均真实波幅', '', '', 'volatility', '6_ml_datasets/l1_l2_factors（A股L1+L2因子训练宽表）'),
    ('vol_true_range', 'vol true range', '', '', 'volatility', '6_ml_datasets/l1_l2_factors（A股L1+L2因子训练宽表）'),
    ('vol_parkinson_10', '10日 Parkinson 波动率', '', '', 'volatility', '6_ml_datasets/l1_l2_factors（A股L1+L2因子训练宽表）'),
    ('vol_parkinson_20', 'Parkinson波动率20日', '', '同上窗口=20', 'volatility', '股票历史日行情信息表后复权.HighPrice/LowPrice'),
    ('vol_gk_10', 'vol Garman-Klass 波动率 10', '', '', 'volatility', '6_ml_datasets/l1_l2_factors（A股L1+L2因子训练宽表）'),
    ('vol_gk_20', 'vol Garman-Klass 波动率 20', '', '', 'volatility', '6_ml_datasets/l1_l2_factors（A股L1+L2因子训练宽表）'),
    ('vol_rs_10', 'vol rs 10', '', '', 'volatility', '6_ml_datasets/l1_l2_factors（A股L1+L2因子训练宽表）'),
    ('vol_rs_20', 'vol rs 20', '', '', 'volatility', '6_ml_datasets/l1_l2_factors（A股L1+L2因子训练宽表）'),
    ('vol_downside_20', '下行波动率20日', '', 'STD(min(ret,0),20)', 'volatility', '股票历史日行情信息表后复权.ClosePrice'),
    ('vol_upside_20', '上行波动率20日', '', 'STD(max(ret,0),20)', 'volatility', '股票历史日行情信息表后复权.ClosePrice'),
    ('vol_realized_rv', '已实现波动率RV (高频当日值，建议使用 Ref(...,1) 以防未来函数)', '', 'HF RV当日值 (建议 Lag 1)', 'volatility', '个股已实现指标表日.RV'),
    ('vol_realized_rrv', '稳健已实现波动率RRV (高频当日值，建议使用 Ref(...,1) 以防未来函数)', '', 'HF RRV当日值 (建议 Lag 1)', 'volatility', '个股已实现指标表日.RRV'),
    ('vol_realized_rskew', '已实现偏度RSkew (高频当日值，建议使用 Ref(...,1) 以防未来函数)', '', 'HF RSkew当日值 (建议 Lag 1)', 'volatility', '个股已实现指标表日.RSkew'),
    ('vol_realized_rkurt', 'vol realized 已实现峰度', '', '', 'volatility', '6_ml_datasets/l1_l2_factors（A股L1+L2因子训练宽表）'),
    ('vol_jump_zadj', '跳跃显著性Z值 (高频当日值，建议使用 Ref(...,1) 以防未来函数)', '', 'HF Z_Adj当日值 (建议 Lag 1)', 'volatility', '个股跳跃指标表日.Z_Adj'),
    ('vol_jump_rjv_ratio', 'vol 跳跃 rjv 比率', '', '', 'volatility', '6_ml_datasets/l1_l2_factors（A股L1+L2因子训练宽表）'),
    ('vol_jump_sjv_ratio', 'vol 跳跃 sjv 比率', '', '', 'volatility', '6_ml_datasets/l1_l2_factors（A股L1+L2因子训练宽表）'),
    ('vol_realized_5min', '5分钟已实现波动率', '', '', 'volatility', 'l2_factors'),
    ('vol_realized_sjv', '连续/跳跃波动率分解-跳跃成分', '', '', 'volatility', 'l2_factors'),
    ('vol_realized_jump', '跳跃波动率', '', '', 'volatility', 'l2_factors'),
    ('vol_skew', '收益率偏度', '分钟成交量分布的偏斜程度', '', 'volatility', 'l2_factors'),
    ('vol_kurtosis', '收益率峰度', '分钟成交量分布的尖峰程度', '', 'volatility', 'l2_factors'),
    ('vol_persistence', '波动率持续性', '', '', 'volatility', 'l2_factors'),
    ('vol_up_down_ratio', '涨跌量比', '', '', 'volatility', 'l2_factors'),
    ('MAX5', '过去5日最高价相对当前价的偏离', '', 'Alpha158 rolling factor', 'volatility', 'feature_snapshots/model_features_*.parquet'),
    ('MIN5', '过去5日最低价相对当前价的偏离', '', 'Alpha158 rolling factor', 'volatility', 'feature_snapshots/model_features_*.parquet'),
    ('MAX10', '过去10日最高价相对当前价的偏离', '', 'Alpha158 rolling factor', 'volatility', 'feature_snapshots/model_features_*.parquet'),
    ('MIN10', '过去10日最低价相对当前价的偏离', '', 'Alpha158 rolling factor', 'volatility', 'feature_snapshots/model_features_*.parquet'),
    ('MAX20', '过去20日最高价相对当前价的偏离', '', 'Alpha158 rolling factor', 'volatility', 'feature_snapshots/model_features_*.parquet'),
    ('MIN20', '过去20日最低价相对当前价的偏离', '', 'Alpha158 rolling factor', 'volatility', 'feature_snapshots/model_features_*.parquet'),
    ('MAX30', '过去30日最高价相对当前价的偏离', '', 'Alpha158 rolling factor', 'volatility', 'feature_snapshots/model_features_*.parquet'),
    ('MIN30', '过去30日最低价相对当前价的偏离', '', 'Alpha158 rolling factor', 'volatility', 'feature_snapshots/model_features_*.parquet'),
    ('MAX60', '过去60日最高价相对当前价的偏离', '', 'Alpha158 rolling factor', 'volatility', 'feature_snapshots/model_features_*.parquet'),
    ('MIN60', '过去60日最低价相对当前价的偏离', '', 'Alpha158 rolling factor', 'volatility', 'feature_snapshots/model_features_*.parquet'),
    ('vol_amp_1', '量价因子', '当日最高价与最低价的相对振幅', '', 'volatility', 'QuantDB L2/衍生特征 (2023-2026 快照回填)'),
    ('vol_amp_20', '量价因子', '近20日单日振幅的统计水平', '', 'volatility', 'QuantDB L2/衍生特征 (2023-2026 快照回填)'),
    ('vol_gini', '量价因子', '分钟成交量分布的不均匀程度', '', 'volatility', 'QuantDB L2/衍生特征 (2023-2026 快照回填)'),
    ('vol_large_trade_intensity', '量价因子', '', '', 'volatility', 'QuantDB L2/衍生特征 (2023-2026 快照回填)'),
    ('vol_price_corr', '量价因子', '', '', 'volatility', 'QuantDB L2/衍生特征 (2023-2026 快照回填)'),
    ('vol_price_divergence', '量价因子', '', '', 'volatility', 'QuantDB L2/衍生特征 (2023-2026 快照回填)'),
    ('vol_realized_10min', '已实现波动率（日内）', '', '', 'volatility', 'QuantDB L2/衍生特征 (2023-2026 快照回填)'),
    ('vol_realized_15min', '已实现波动率（日内）', '', '', 'volatility', 'QuantDB L2/衍生特征 (2023-2026 快照回填)'),
    ('vol_realized_am', '已实现波动率（日内）', '', '', 'volatility', 'QuantDB L2/衍生特征 (2023-2026 快照回填)'),
    ('vol_realized_closing', '已实现波动率（日内）', '', '', 'volatility', 'QuantDB L2/衍生特征 (2023-2026 快照回填)'),
    ('vol_realized_opening', '已实现波动率（日内）', '', '', 'volatility', 'QuantDB L2/衍生特征 (2023-2026 快照回填)'),
    ('vol_realized_pm', '已实现波动率（日内）', '', '', 'volatility', 'QuantDB L2/衍生特征 (2023-2026 快照回填)'),
    ('vol_tick_density', '量价因子', '单位时间内的成交笔数', '', 'volatility', 'QuantDB L2/衍生特征 (2023-2026 快照回填)'),
    ('vol_to_ma5', '量价因子', '', '', 'volatility', 'QuantDB L2/衍生特征 (2023-2026 快照回填)'),
    ('vol_turnover_am_pm', '成交分布（日内）', '', '', 'volatility', 'QuantDB L2/衍生特征 (2023-2026 快照回填)'),
    ('vol_turnover_close', '成交分布（日内）', '', '', 'volatility', 'QuantDB L2/衍生特征 (2023-2026 快照回填)'),
    ('vol_turnover_concentration', '成交分布（日内）', '', '', 'volatility', 'QuantDB L2/衍生特征 (2023-2026 快照回填)'),
    ('vol_turnover_open', '成交分布（日内）', '', '', 'volatility', 'QuantDB L2/衍生特征 (2023-2026 快照回填)'),
    ('vol_turnover_total', '成交分布（日内）', '', '', 'volatility', 'QuantDB L2/衍生特征 (2023-2026 快照回填)'),
    ('liq_turnover_os', '流通换手率', '当日成交量/流通股本', 'ToverOs', 'liquidity', '个股换手率表日.ToverOs'),
    ('liq_turnover_tl', '换手率等权均值', '', '', 'liquidity', '6_ml_datasets/l1_l2_factors（A股L1+L2因子训练宽表）'),
    ('liq_volume', '当日成交量', '当日成交量', 'Volume_t', 'liquidity', '股票历史日行情信息表后复权.Volume'),
    ('liq_volume_ma_5', '5日均成交量', '', '', 'liquidity', '6_ml_datasets/l1_l2_factors（A股L1+L2因子训练宽表）'),
    ('liq_volume_ma_10', '10日均成交量', '', '', 'liquidity', '6_ml_datasets/l1_l2_factors（A股L1+L2因子训练宽表）'),
    ('liq_volume_ma_20', '20日均成交量', '', '', 'liquidity', '6_ml_datasets/l1_l2_factors（A股L1+L2因子训练宽表）'),
    ('liq_volume_ratio_5', '量比(5日)', '', 'Volume/MA(Volume,5)', 'liquidity', '股票历史日行情信息表后复权.Volume'),
    ('liq_volume_ratio_20', '成交量20日斜率', '', '', 'liquidity', '6_ml_datasets/l1_l2_factors（A股L1+L2因子训练宽表）'),
    ('liq_amount', '当日成交额', '当日成交额', 'Amount_t', 'liquidity', '股票历史日行情信息表后复权.Amount'),
    ('liq_amount_ma_5', '5日均成交额', '', '', 'liquidity', '6_ml_datasets/l1_l2_factors（A股L1+L2因子训练宽表）'),
    ('liq_amount_ma_10', '10日均成交额', '', '', 'liquidity', '6_ml_datasets/l1_l2_factors（A股L1+L2因子训练宽表）'),
    ('liq_amount_ma_20', '20日均成交额', '', '', 'liquidity', '6_ml_datasets/l1_l2_factors（A股L1+L2因子训练宽表）'),
    ('liq_amount_ratio_5', '成交额5日斜率', '', '', 'liquidity', '6_ml_datasets/l1_l2_factors（A股L1+L2因子训练宽表）'),
    ('liq_amount_ratio_20', '成交额20日斜率', '', '', 'liquidity', '6_ml_datasets/l1_l2_factors（A股L1+L2因子训练宽表）'),
    ('liq_trade_count', '成交笔数', '', '', 'liquidity', 'feature_snapshots/model_features_*.parquet'),
    ('liq_avg_trade_size', '平均单笔成交额', '', '', 'liquidity', 'feature_snapshots/model_features_*.parquet'),
    ('liq_obv_20', '20日OBV能量潮', '基于成交量累计的能量潮指标20日口径', '', 'liquidity', '6_ml_datasets/l1_l2_factors（A股L1+L2因子训练宽表）'),
    ('liq_obv_60', '60日OBV能量潮', '', '', 'liquidity', '6_ml_datasets/l1_l2_factors（A股L1+L2因子训练宽表）'),
    ('liq_mfi_14', '资金流量指标MFI14', '基于典型价格与成交量的资金流强弱指标', 'MFI窗口14', 'liquidity', '股票历史日行情信息表后复权.HighPrice,LowPrice,ClosePrice,Amount'),
    ('liq_accdist_20', '20日累积/派发线(ADL)', '', '', 'liquidity', '6_ml_datasets/l1_l2_factors（A股L1+L2因子训练宽表）'),
    ('liq_amihud_20', 'Amihud非流动性20日', '近20日|收益|/成交额均值的对数口径，衡量价格冲击', 'MA(|ret|/Amount,20)', 'liquidity', '股票历史日行情信息表后复权.ClosePrice,Amount'),
    ('liq_amihud_60', '60日Amihud非流动性', '', '', 'liquidity', '6_ml_datasets/l1_l2_factors（A股L1+L2因子训练宽表）'),
    ('vol_to_ma20', '成交量/20日均量', '', 'volume / volume_ma_20', 'liquidity', 'features_daily'),
    ('volume_ma_3', '3日均量', '', 'MA(volume, 3)', 'liquidity', 'features_daily'),
    ('volume_trend_3d', '3日成交量趋势', '', 'volume / volume_shift_3d - 1', 'liquidity', 'features_daily'),
    ('amount_ma_5', '成交额5日均(原始口径, 覆盖率优于 liq_amount_ma_5)', '', 'MA(amount, 5)', 'liquidity', 'feature_snapshots/model_features_*.parquet'),
    ('turn_1', '换手率因子', '', '', 'liquidity', 'QuantDB L2/衍生特征 (2023-2026 快照回填)'),
    ('turn_10', '换手率因子', '', '', 'liquidity', 'QuantDB L2/衍生特征 (2023-2026 快照回填)'),
    ('turn_20', '换手率因子', '', '', 'liquidity', 'QuantDB L2/衍生特征 (2023-2026 快照回填)'),
    ('turn_3', '换手率因子', '', '', 'liquidity', 'QuantDB L2/衍生特征 (2023-2026 快照回填)'),
    ('turn_5', '换手率因子', '', '', 'liquidity', 'QuantDB L2/衍生特征 (2023-2026 快照回填)'),
    ('turn_60', '换手率因子', '', '', 'liquidity', 'QuantDB L2/衍生特征 (2023-2026 快照回填)'),
    ('turn_acc_20', '累计换手率', '', '', 'liquidity', 'QuantDB L2/衍生特征 (2023-2026 快照回填)'),
    ('turn_acc_5', '累计换手率', '', '', 'liquidity', 'QuantDB L2/衍生特征 (2023-2026 快照回填)'),
    ('turn_breakout_20', '换手率因子', '', '', 'liquidity', 'QuantDB L2/衍生特征 (2023-2026 快照回填)'),
    ('turn_high_days_10', '换手率因子', '', '', 'liquidity', 'QuantDB L2/衍生特征 (2023-2026 快照回填)'),
    ('turn_hl_pos_20', '换手率因子', '', '', 'liquidity', 'QuantDB L2/衍生特征 (2023-2026 快照回填)'),
    ('turn_ratio_1_20', '换手率因子', '', '', 'liquidity', 'QuantDB L2/衍生特征 (2023-2026 快照回填)'),
    ('turn_ratio_1_5', '换手率因子', '', '', 'liquidity', 'QuantDB L2/衍生特征 (2023-2026 快照回填)'),
    ('turn_std_20', '换手率因子', '', '', 'liquidity', 'QuantDB L2/衍生特征 (2023-2026 快照回填)'),
    ('turn_trend_5_20', '换手率因子', '', '', 'liquidity', 'QuantDB L2/衍生特征 (2023-2026 快照回填)'),
    ('turn_z_20', '换手率因子', '(当日换手率-20日均值)/20日标准差，捕捉换手率异常放大', '', 'liquidity', 'QuantDB L2/衍生特征 (2023-2026 快照回填)'),
    ('flow_net_amount', '总净流入额', '', 'B_Amount-S_Amount', 'fund_flow', '个股买卖不平衡指标表日.B_Amount,S_Amount'),
    ('flow_net_amount_ratio', '总净流入占比', '', '(B_Amount-S_Amount)/(B_Amount+S_Amount)', 'fund_flow', '个股买卖不平衡指标表日.B_Amount,S_Amount'),
    ('flow_large_net_amount', '大单净流入额', '', 'B_Amount_L-S_Amount_L', 'fund_flow', '个股买卖不平衡指标表日.B_Amount_L,S_Amount_L'),
    ('flow_large_net_ratio', '资金流 大单 净流入 比率', '', '', 'fund_flow', '6_ml_datasets/l1_l2_factors（A股L1+L2因子训练宽表）'),
    ('flow_medium_net_amount', '资金流 中单 净流入 成交额', '', '', 'fund_flow', '6_ml_datasets/l1_l2_factors（A股L1+L2因子训练宽表）'),
    ('flow_medium_net_ratio', '资金流 中单 净流入 比率', '', '', 'fund_flow', '6_ml_datasets/l1_l2_factors（A股L1+L2因子训练宽表）'),
    ('flow_small_net_amount', '资金流 小单 净流入 成交额', '', '', 'fund_flow', '6_ml_datasets/l1_l2_factors（A股L1+L2因子训练宽表）'),
    ('flow_small_net_ratio', '资金流 小单 净流入 比率', '', '', 'fund_flow', '6_ml_datasets/l1_l2_factors（A股L1+L2因子训练宽表）'),
    ('flow_net_order_count', '资金流 净流入 委托 次数', '', '', 'fund_flow', '6_ml_datasets/l1_l2_factors（A股L1+L2因子训练宽表）'),
    ('flow_net_order_ratio', '资金流 净流入 委托 比率', '', '', 'fund_flow', '6_ml_datasets/l1_l2_factors（A股L1+L2因子训练宽表）'),
    ('flow_large_net_order', '资金流 大单 净流入 委托', '', '', 'fund_flow', '6_ml_datasets/l1_l2_factors（A股L1+L2因子训练宽表）'),
    ('flow_large_order_ratio', '资金流 大单 委托 比率', '', '', 'fund_flow', '6_ml_datasets/l1_l2_factors（A股L1+L2因子训练宽表）'),
    ('flow_vpin', 'VPIN当日值', '', 'VPIN_t', 'fund_flow', '个股知情交易概率指标表日.VPIN'),
    ('flow_vpin_ma_5', 'VPIN五日均值', '', 'MA(VPIN,5)', 'fund_flow', '个股知情交易概率指标表日.VPIN'),
    ('flow_vpin_ma_20', 'VPIN二十日均值', '', 'MA(VPIN,20)', 'fund_flow', '个股知情交易概率指标表日.VPIN'),
    ('flow_vpin_delta_5', '资金流 VPIN delta 5', '', '', 'fund_flow', '6_ml_datasets/l1_l2_factors（A股L1+L2因子训练宽表）'),
    ('flow_qsp', '资金流 qsp', '', '', 'fund_flow', '6_ml_datasets/l1_l2_factors（A股L1+L2因子训练宽表）'),
    ('flow_esp', '资金流 esp', '', '', 'fund_flow', '6_ml_datasets/l1_l2_factors（A股L1+L2因子训练宽表）'),
    ('flow_aqsp', '资金流 aqsp', '', '', 'fund_flow', '6_ml_datasets/l1_l2_factors（A股L1+L2因子训练宽表）'),
    ('flow_qsp_time', '资金流 qsp 时间加权', '', '', 'fund_flow', '6_ml_datasets/l1_l2_factors（A股L1+L2因子训练宽表）'),
    ('flow_esp_time', '资金流 esp 时间加权', '', '', 'fund_flow', '6_ml_datasets/l1_l2_factors（A股L1+L2因子训练宽表）'),
    ('flow_pressure_index', '资金压力指数', '', 'z(flow_net_amount)+z(VPIN)+z(Esp)', 'fund_flow', '个股买卖不平衡指标表日 + 个股知情交易概率指标表日 + 个股买卖价差表日'),
    ('flow_net_ratio', '总净流入占比', '', '', 'fund_flow', 'l2_factors'),
    ('flow_large_net', '大单净流入', '', '', 'fund_flow', 'l2_factors'),
    ('flow_medium_net', '中单净流入', '', '', 'fund_flow', 'l2_factors'),
    ('flow_small_net', '小单净流入', '', '', 'fund_flow', 'l2_factors'),
    ('flow_super_net', '超大单净流入', '', '', 'fund_flow', 'l2_factors'),
    ('flow_large_ratio', '大单流入占比', '', '', 'fund_flow', 'l2_factors'),
    ('flow_medium_ratio', '中单流入占比', '', '', 'fund_flow', 'l2_factors'),
    ('flow_small_ratio', '小单流入占比', '', '', 'fund_flow', 'l2_factors'),
    ('flow_imbalance_volume', '委托量不平衡', '', '', 'fund_flow', 'l2_factors'),
    ('flow_consistency', '资金流一致性', '', '', 'fund_flow', 'l2_factors'),
    ('flow_money_flow_index', '资金流量指数', '', '', 'fund_flow', 'l2_factors'),
    ('flow_big_trade_ratio', '大单成交占比', '', '', 'fund_flow', 'l2_factors'),
    ('micro_vpin_8', 'VPIN(8桶)', '', '', 'fund_flow', 'l2_factors'),
    ('micro_vpin_20', 'VPIN(20桶)', '', '', 'fund_flow', 'l2_factors'),
    ('micro_vpin_50', 'VPIN(50桶)', '', '', 'fund_flow', 'l2_factors'),
    ('micro_vpin_ma_5', 'VPIN 5日均值', '', '', 'fund_flow', 'l2_factors'),
    ('micro_vpin_ma_20', 'VPIN 20日均值', '', '', 'fund_flow', 'l2_factors'),
    ('micro_vpin_delta_5', 'VPIN 5日变化', '', '', 'fund_flow', 'l2_factors'),
    ('micro_pin', 'PIN知情交易概率', '', '', 'fund_flow', 'l2_factors'),
    ('amt_close_pos', '收盘时段成交占比', '当前成交额在近期区间中的相对位置', '', 'fund_flow', 'QuantDB L2/衍生特征 (2023-2026 快照回填)'),
    ('amt_high_days_10', '近10日成交额新高天数', '', '', 'fund_flow', 'QuantDB L2/衍生特征 (2023-2026 快照回填)'),
    ('amt_log', '成交额对数', '当日成交额的对数，衡量资金活跃度', '', 'fund_flow', 'QuantDB L2/衍生特征 (2023-2026 快照回填)'),
    ('amt_ma_20', 'N日平均成交额', '', '', 'fund_flow', 'QuantDB L2/衍生特征 (2023-2026 快照回填)'),
    ('amt_ma_5', 'N日平均成交额', '', '', 'fund_flow', 'QuantDB L2/衍生特征 (2023-2026 快照回填)'),
    ('amt_ma_60', 'N日平均成交额', '', '', 'fund_flow', 'QuantDB L2/衍生特征 (2023-2026 快照回填)'),
    ('amt_net_flow_20', 'N日净资金流（成交额口径）', '', '', 'fund_flow', 'QuantDB L2/衍生特征 (2023-2026 快照回填)'),
    ('amt_net_flow_5', 'N日净资金流（成交额口径）', '', '', 'fund_flow', 'QuantDB L2/衍生特征 (2023-2026 快照回填)'),
    ('amt_ratio_1_20', '成交额比值（短/长窗口）', '', '', 'fund_flow', 'QuantDB L2/衍生特征 (2023-2026 快照回填)'),
    ('amt_ratio_1_5', '成交额比值（短/长窗口）', '', '', 'fund_flow', 'QuantDB L2/衍生特征 (2023-2026 快照回填)'),
    ('amt_ratio_5_20', '成交额比值（短/长窗口）', '', '', 'fund_flow', 'QuantDB L2/衍生特征 (2023-2026 快照回填)'),
    ('amt_skew_20', '成交额偏度', '', '', 'fund_flow', 'QuantDB L2/衍生特征 (2023-2026 快照回填)'),
    ('amt_up_ratio_20', '上涨日成交额占比', '', '', 'fund_flow', 'QuantDB L2/衍生特征 (2023-2026 快照回填)'),
    ('amt_up_ratio_5', '上涨日成交额占比', '', '', 'fund_flow', 'QuantDB L2/衍生特征 (2023-2026 快照回填)'),
    ('amt_vol_ratio_20', '成交额/波动比', '', '', 'fund_flow', 'QuantDB L2/衍生特征 (2023-2026 快照回填)'),
    ('amt_z_20', '成交额20日Z分数', '当前成交额相对近20日均值的标准化偏离', '', 'fund_flow', 'QuantDB L2/衍生特征 (2023-2026 快照回填)'),
    ('flow_buy_amount', '主动买入金额', '', '', 'fund_flow', 'QuantDB L2/衍生特征 (2023-2026 快照回填)'),
    ('flow_buy_ratio', '主动买入占比', '', '', 'fund_flow', 'QuantDB L2/衍生特征 (2023-2026 快照回填)'),
    ('flow_sell_amount', '主动卖出金额', '', '', 'fund_flow', 'QuantDB L2/衍生特征 (2023-2026 快照回填)'),
    ('flow_sell_ratio', '主动卖出占比', '', '', 'fund_flow', 'QuantDB L2/衍生特征 (2023-2026 快照回填)'),
    ('flow_super_ratio', 'L2资金流因子', '', '', 'fund_flow', 'QuantDB L2/衍生特征 (2023-2026 快照回填)'),
    ('style_ln_mv_total', '总市值对数', '', 'ln(MarketValue)', 'style', '股票历史日行情信息表后复权.MarketValue'),
    ('style_ln_mv_float', '流通市值对数', '', 'ln(CirculatedMarketValue)', 'style', '股票历史日行情信息表后复权.CirculatedMarketValue'),
    ('style_bp', '账面市净率倒数(B/P)', '', '1/PB', 'style', '相对价值指标.pb_ratio'),
    ('style_ep_ttm', '盈利收益率(E/P)', '', '1/PE_TTM', 'style', '相对价值指标.pe_ratio_ttm'),
    ('style_smb', 'style smb', '', '', 'style', '6_ml_datasets/l1_l2_factors（A股L1+L2因子训练宽表）'),
    ('style_hml', 'style hml', '', '', 'style', '6_ml_datasets/l1_l2_factors（A股L1+L2因子训练宽表）'),
    ('style_mkt_premium', 'style mkt premium', '', '', 'style', '6_ml_datasets/l1_l2_factors（A股L1+L2因子训练宽表）'),
    ('style_beta_20', '20日市场Beta', '', 'cov(ret,mkt)/var(mkt),window=20', 'style', '股票历史日行情信息表后复权.ChangeRatio + 指数文件.Retindex'),
    ('style_beta_60', '60日市场Beta', '', 'window=60', 'style', '股票历史日行情信息表后复权.ChangeRatio + 指数文件.Retindex'),
    ('style_beta_120', '120日市场 Beta', '', '', 'style', '6_ml_datasets/l1_l2_factors（A股L1+L2因子训练宽表）'),
    ('style_idio_vol_20', '20日特质波动', '', 'STD(ret-beta*mkt,20)', 'style', '股票历史日行情信息表后复权 + 指数文件'),
    ('style_idio_vol_60', '60日特质波动率', '', '', 'style', '6_ml_datasets/l1_l2_factors（A股L1+L2因子训练宽表）'),
    ('style_residual_ret_20', '20日残差收益', '剔除市场Beta后的特质收益累计，残差动量因子', 'sum(ret-beta*mkt,20)', 'style', '股票历史日行情信息表后复权 + 指数文件'),
    ('style_valuation_composite', 'style valuation composite', '', '', 'style', '6_ml_datasets/l1_l2_factors（A股L1+L2因子训练宽表）'),
    ('style_size_percentile', 'style 规模 percentile', '', '', 'style', '6_ml_datasets/l1_l2_factors（A股L1+L2因子训练宽表）'),
    ('style_value_percentile', 'style value percentile', '', '', 'style', '6_ml_datasets/l1_l2_factors（A股L1+L2因子训练宽表）'),
    ('style_size_20', '规模因子20日', '', '', 'style', 'l1_factors'),
    ('style_value_20', '价值因子20日', '', '', 'style', 'l1_factors'),
    ('beta_20', '20日Beta（对市场）', '', '', 'style', 'QuantDB L2/衍生特征 (2023-2026 快照回填)'),
    ('ind_ret_1d', '所属行业1日收益', '', 'industry_mean(ret,1d)', 'industry', '股票历史日行情信息表后复权.ChangeRatio + 公司文件.Indcd'),
    ('ind_ret_5d', 'ind 收益率 5d', '', '', 'industry', '6_ml_datasets/l1_l2_factors（A股L1+L2因子训练宽表）'),
    ('ind_ret_10d', 'ind 收益率 10d', '', '', 'industry', '6_ml_datasets/l1_l2_factors（A股L1+L2因子训练宽表）'),
    ('ind_ret_20d', '所属行业20日收益', '', 'industry_mean(ret,20d)', 'industry', '股票历史日行情信息表后复权.ChangeRatio + 公司文件.Indcd'),
    ('ind_vol_20', 'ind vol 20', '', '', 'industry', '6_ml_datasets/l1_l2_factors（A股L1+L2因子训练宽表）'),
    ('ind_turnover_20', 'ind 换手率 20', '', '', 'industry', '6_ml_datasets/l1_l2_factors（A股L1+L2因子训练宽表）'),
    ('ind_amount_20', 'ind 成交额 20', '', '', 'industry', '6_ml_datasets/l1_l2_factors（A股L1+L2因子训练宽表）'),
    ('ind_strength_20', '个股相对行业强度20日', '个股20日收益-所属行业20日均值收益，行业内的超额强度', 'ret_20d-ind_ret_20d', 'industry', '股票历史日行情信息表后复权 + 公司文件.Indcd'),
    ('ind_strength_60', 'ind strength 60', '', '', 'industry', '6_ml_datasets/l1_l2_factors（A股L1+L2因子训练宽表）'),
    ('ind_dispersion_20', 'ind dispersion 20', '', '', 'industry', '6_ml_datasets/l1_l2_factors（A股L1+L2因子训练宽表）'),
    ('ind_up_breadth_20', 'ind up breadth 20', '', '', 'industry', '6_ml_datasets/l1_l2_factors（A股L1+L2因子训练宽表）'),
    ('ind_down_breadth_20', 'ind down breadth 20', '', '', 'industry', '6_ml_datasets/l1_l2_factors（A股L1+L2因子训练宽表）'),
    ('ind_relative_volume_20', 'ind relative 成交量 20', '', '', 'industry', '6_ml_datasets/l1_l2_factors（A股L1+L2因子训练宽表）'),
    ('ind_relative_volatility_20', 'ind relative 波动率 20', '', '', 'industry', '6_ml_datasets/l1_l2_factors（A股L1+L2因子训练宽表）'),
    ('ind_relative_flow_20', 'ind relative 资金流 20', '', '', 'industry', '6_ml_datasets/l1_l2_factors（A股L1+L2因子训练宽表）'),
    ('ind_momentum_rank_20', '行业动量排名', '', 'rank(ind_ret_20)', 'industry', '股票历史日行情信息表后复权 + 公司文件.Indcd'),
    ('ind_value_rank', 'ind value rank', '', '', 'industry', '6_ml_datasets/l1_l2_factors（A股L1+L2因子训练宽表）'),
    ('ind_size_rank', 'ind 规模 rank', '', '', 'industry', '6_ml_datasets/l1_l2_factors（A股L1+L2因子训练宽表）'),
    ('ind_code_l1', 'ind code l1', '', '', 'industry', '6_ml_datasets/l1_l2_factors（A股L1+L2因子训练宽表）'),
    ('ind_code_l2', 'ind code l2', '', '', 'industry', '6_ml_datasets/l1_l2_factors（A股L1+L2因子训练宽表）'),
    ('ind_ret_5', '行业5日收益', '', '', 'industry', 'l1_factors'),
    ('ind_ret_10', '行业10日收益', '', '', 'industry', 'l1_factors'),
    ('ind_ret_20', '行业20日收益', '', '', 'industry', 'l1_factors'),
    ('ind_rotation_speed_20', '行业轮动速度', '', '', 'industry', 'l1_factors'),
    ('ind_breadth_up_20', '行业上涨广度', '', '', 'industry', 'l1_factors'),
    ('ind_volume_ratio_20', '行业量比', '', '', 'industry', 'l1_factors'),
    ('ind_crowding_20', '行业拥挤度', '', '', 'industry', 'l1_factors'),
    ('ind_netflow_rank_20', '行业资金流排名', '', '', 'industry', 'l1_factors'),
    ('ind_relative_pe', '行业相对PE', '', '', 'industry', 'l1_factors'),
    ('ind_concentration', '行业集中度', '', '', 'industry', 'l1_factors'),
    ('ind_relative_momentum_20', '行业相对动量', '', '', 'industry', 'l1_factors'),
    ('ind_momentum_decay', '行业动量衰减', '', '', 'industry', 'l1_factors'),
    ('micro_qsp_equal', 'qsp 等权', '', '', 'microstructure', '6_ml_datasets/l1_l2_factors（A股L1+L2因子训练宽表）'),
    ('micro_esp_equal', 'esp 等权', '', '', 'microstructure', '6_ml_datasets/l1_l2_factors（A股L1+L2因子训练宽表）'),
    ('micro_aqsp_equal', 'aqsp 等权', '', '', 'microstructure', '6_ml_datasets/l1_l2_factors（A股L1+L2因子训练宽表）'),
    ('micro_qsp_time', 'qsp 时间加权', '', '', 'microstructure', '6_ml_datasets/l1_l2_factors（A股L1+L2因子训练宽表）'),
    ('micro_esp_time', 'esp 时间加权', '', '', 'microstructure', '6_ml_datasets/l1_l2_factors（A股L1+L2因子训练宽表）'),
    ('micro_qsp_volume', 'qsp 成交量', '', '', 'microstructure', '6_ml_datasets/l1_l2_factors（A股L1+L2因子训练宽表）'),
    ('micro_esp_volume', 'esp 成交量', '', '', 'microstructure', '6_ml_datasets/l1_l2_factors（A股L1+L2因子训练宽表）'),
    ('micro_qsp_amount', 'qsp 成交额', '', '', 'microstructure', '6_ml_datasets/l1_l2_factors（A股L1+L2因子训练宽表）'),
    ('micro_esp_amount', 'esp 成交额', '', '', 'microstructure', '6_ml_datasets/l1_l2_factors（A股L1+L2因子训练宽表）'),
    ('micro_effective_spread', '有效 价差', '', '', 'microstructure', '6_ml_datasets/l1_l2_factors（A股L1+L2因子训练宽表）'),
    ('micro_quoted_spread', 'quoted 价差', '', '', 'microstructure', '6_ml_datasets/l1_l2_factors（A股L1+L2因子训练宽表）'),
    ('micro_spread_vol_20', '价差 vol 20', '', '', 'microstructure', '6_ml_datasets/l1_l2_factors（A股L1+L2因子训练宽表）'),
    ('micro_imbalance_volume', '不平衡度 成交量', '', '', 'microstructure', '6_ml_datasets/l1_l2_factors（A股L1+L2因子训练宽表）'),
    ('micro_imbalance_amount', '不平衡度 成交额', '', '', 'microstructure', '6_ml_datasets/l1_l2_factors（A股L1+L2因子训练宽表）'),
    ('micro_imbalance_count', '不平衡度 次数', '', '', 'microstructure', '6_ml_datasets/l1_l2_factors（A股L1+L2因子训练宽表）'),
    ('micro_imbalance_large', '不平衡度 大单', '', '', 'microstructure', '6_ml_datasets/l1_l2_factors（A股L1+L2因子训练宽表）'),
    ('micro_imbalance_medium', '不平衡度 中单', '', '', 'microstructure', '6_ml_datasets/l1_l2_factors（A股L1+L2因子训练宽表）'),
    ('micro_imbalance_small', '不平衡度 小单', '', '', 'microstructure', '6_ml_datasets/l1_l2_factors（A股L1+L2因子训练宽表）'),
    ('micro_jump_flag', '跳跃 标记', '', '', 'microstructure', '6_ml_datasets/l1_l2_factors（A股L1+L2因子训练宽表）'),
    ('micro_pressure_score', 'pressure 评分', '', '', 'microstructure', '6_ml_datasets/l1_l2_factors（A股L1+L2因子训练宽表）'),
    ('micro_amihud_illiquidity', 'Amihud非流动性', '', '', 'microstructure', 'l2_factors'),
    ('micro_kyle_lambda', 'Kyle Lambda价格冲击', '', '', 'microstructure', 'l2_factors'),
    ('micro_price_impact_large', '大单价格冲击', '', '', 'microstructure', 'l2_factors'),
    ('micro_impact_cost', '冲击成本', '', '', 'microstructure', 'l2_factors'),
    ('micro_impact_elasticity', '冲击弹性', '', '', 'microstructure', 'l2_factors'),
    ('micro_aqsp', '调整报价价差', '调整后的报价价差指标', '', 'microstructure', 'l2_factors'),
    ('micro_aesp', '调整有效价差', '调整后的有效价差指标', '', 'microstructure', 'l2_factors'),
    ('micro_qsp_vol_20', '报价价差波动20日', '', '', 'microstructure', 'l2_factors'),
    ('micro_esp_vol_20', '有效价差波动20日', '', '', 'microstructure', 'l2_factors'),
    ('micro_spread_slope_1_5', '价差斜率1-5档', '', '', 'microstructure', 'l2_factors'),
    ('micro_bid_ask_vol_ratio', '买卖量比', '', '', 'microstructure', 'l2_factors'),
    ('micro_depth_imbalance_1', '1档深度不平衡', '', '', 'microstructure', 'l2_factors'),
    ('micro_depth_imbalance_5', '5档深度不平衡', '', '', 'microstructure', 'l2_factors'),
    ('micro_depth_slope', '深度斜率', '', '', 'microstructure', 'l2_factors'),
    ('micro_order_flow_toxicity', '订单流毒性', '', '', 'microstructure', 'l2_factors'),
    ('micro_informed_ratio', '知情交易者比例', '', '', 'microstructure', 'l2_factors'),
    ('micro_jump_count_1pct', '跳跃次数(1%阈值)', '', '', 'microstructure', 'l2_factors'),
    ('micro_open_gap', '开盘缺口', '', '', 'microstructure', 'l2_factors'),
    ('micro_trade_buy_pressure', '买方压力', '', '', 'microstructure', 'l2_factors'),
    ('micro_trade_sell_pressure', '卖方压力', '', '', 'microstructure', 'l2_factors'),
    ('flow_cancel_buy_rate', '买单撤单率', '', '', 'microstructure', 'QuantDB L2/衍生特征 (2023-2026 快照回填)'),
    ('flow_cancel_cluster', '撤单聚集度', '', '', 'microstructure', 'QuantDB L2/衍生特征 (2023-2026 快照回填)'),
    ('flow_cancel_depth_dist', '撤单距盘口深度', '', '', 'microstructure', 'QuantDB L2/衍生特征 (2023-2026 快照回填)'),
    ('flow_cancel_hft_ratio', '高频撤单占比', '', '', 'microstructure', 'QuantDB L2/衍生特征 (2023-2026 快照回填)'),
    ('flow_cancel_imbalance', '撤单方向不平衡', '', '', 'microstructure', 'QuantDB L2/衍生特征 (2023-2026 快照回填)'),
    ('flow_cancel_lifetime', '撤单前挂单存活时间', '', '', 'microstructure', 'QuantDB L2/衍生特征 (2023-2026 快照回填)'),
    ('flow_cancel_post_price_change', '撤单后价格变动', '', '', 'microstructure', 'QuantDB L2/衍生特征 (2023-2026 快照回填)'),
    ('flow_cancel_price_deviation', '撤单价偏离', '', '', 'microstructure', 'QuantDB L2/衍生特征 (2023-2026 快照回填)'),
    ('flow_cancel_rate', '总撤单率', '', '', 'microstructure', 'QuantDB L2/衍生特征 (2023-2026 快照回填)'),
    ('flow_cancel_sell_rate', '卖单撤单率', '', '', 'microstructure', 'QuantDB L2/衍生特征 (2023-2026 快照回填)'),
    ('flow_cancel_spoof', '幌骗(Spoofing)撤单信号', '', '', 'microstructure', 'QuantDB L2/衍生特征 (2023-2026 快照回填)'),
    ('flow_imbalance_autocorr', '委托失衡（时序/盘中）', '', '', 'microstructure', 'QuantDB L2/衍生特征 (2023-2026 快照回填)'),
    ('flow_imbalance_close', '委托失衡（时序/盘中）', '', '', 'microstructure', 'QuantDB L2/衍生特征 (2023-2026 快照回填)'),
    ('flow_imbalance_mid_am', '委托失衡（时序/盘中）', '', '', 'microstructure', 'QuantDB L2/衍生特征 (2023-2026 快照回填)'),
    ('flow_imbalance_mid_pm', '委托失衡（时序/盘中）', '', '', 'microstructure', 'QuantDB L2/衍生特征 (2023-2026 快照回填)'),
    ('flow_imbalance_open', '委托失衡（时序/盘中）', '', '', 'microstructure', 'QuantDB L2/衍生特征 (2023-2026 快照回填)'),
    ('flow_imbalance_revert_speed', '委托失衡（时序/盘中）', '', '', 'microstructure', 'QuantDB L2/衍生特征 (2023-2026 快照回填)'),
    ('flow_large_pct', '大单成交占比', '', '', 'microstructure', 'QuantDB L2/衍生特征 (2023-2026 快照回填)'),
    ('flow_order_arrival_rate', '订单到达速率', '', '', 'microstructure', 'QuantDB L2/衍生特征 (2023-2026 快照回填)'),
    ('flow_order_book_rebuild', '盘口重建速度', '', '', 'microstructure', 'QuantDB L2/衍生特征 (2023-2026 快照回填)'),
    ('flow_order_duration_p50', '订单存活时间P50', '', '', 'microstructure', 'QuantDB L2/衍生特征 (2023-2026 快照回填)'),
    ('flow_order_duration_p90', '订单存活时间P90', '', '', 'microstructure', 'QuantDB L2/衍生特征 (2023-2026 快照回填)'),
    ('flow_order_imbalance', '订单不平衡', '', '', 'microstructure', 'QuantDB L2/衍生特征 (2023-2026 快照回填)'),
    ('flow_order_large_ratio', '大单订单占比', '', '', 'microstructure', 'QuantDB L2/衍生特征 (2023-2026 快照回填)'),
    ('flow_order_quality', '订单质量', '', '', 'microstructure', 'QuantDB L2/衍生特征 (2023-2026 快照回填)'),
    ('flow_order_size_skew', '订单微观属性', '', '', 'microstructure', 'QuantDB L2/衍生特征 (2023-2026 快照回填)'),
    ('flow_order_type_diversity', '订单微观属性', '', '', 'microstructure', 'QuantDB L2/衍生特征 (2023-2026 快照回填)'),
    ('micro_adverse_selection', 'L2微观结构-逆向选择', '', '', 'microstructure', 'QuantDB L2/衍生特征 (2023-2026 快照回填)'),
    ('micro_adverse_selection_cost', 'L2微观结构-逆向选择', '', '', 'microstructure', 'QuantDB L2/衍生特征 (2023-2026 快照回填)'),
    ('micro_call_auction_depth_change', 'L2微观结构-集合竞价', '', '', 'microstructure', 'QuantDB L2/衍生特征 (2023-2026 快照回填)'),
    ('micro_call_auction_vol_ratio', 'L2微观结构-集合竞价', '', '', 'microstructure', 'QuantDB L2/衍生特征 (2023-2026 快照回填)'),
    ('micro_close_auction_impact', 'L2微观结构-收盘竞价', '', '', 'microstructure', 'QuantDB L2/衍生特征 (2023-2026 快照回填)'),
    ('micro_close_squeeze', 'L2微观结构-收盘挤压', '', '', 'microstructure', 'QuantDB L2/衍生特征 (2023-2026 快照回填)'),
    ('micro_depth_ask', 'L2微观结构-盘口深度', '', '', 'microstructure', 'QuantDB L2/衍生特征 (2023-2026 快照回填)'),
    ('micro_depth_bid', 'L2微观结构-盘口深度', '', '', 'microstructure', 'QuantDB L2/衍生特征 (2023-2026 快照回填)'),
    ('micro_depth_close', 'L2微观结构-盘口深度', '', '', 'microstructure', 'QuantDB L2/衍生特征 (2023-2026 快照回填)'),
    ('micro_depth_concentration_ask', 'L2微观结构-盘口深度', '', '', 'microstructure', 'QuantDB L2/衍生特征 (2023-2026 快照回填)'),
    ('micro_depth_concentration_bid', 'L2微观结构-盘口深度', '', '', 'microstructure', 'QuantDB L2/衍生特征 (2023-2026 快照回填)'),
    ('micro_depth_effective', 'L2微观结构-盘口深度', '', '', 'microstructure', 'QuantDB L2/衍生特征 (2023-2026 快照回填)'),
    ('micro_depth_extreme', 'L2微观结构-盘口深度', '', '', 'microstructure', 'QuantDB L2/衍生特征 (2023-2026 快照回填)'),
    ('micro_depth_imbalance_10', 'L2微观结构-盘口深度', '', '', 'microstructure', 'QuantDB L2/衍生特征 (2023-2026 快照回填)'),
    ('micro_depth_mid', 'L2微观结构-盘口深度', '', '', 'microstructure', 'QuantDB L2/衍生特征 (2023-2026 快照回填)'),
    ('micro_depth_open', 'L2微观结构-盘口深度', '', '', 'microstructure', 'QuantDB L2/衍生特征 (2023-2026 快照回填)'),
    ('micro_depth_ratio_1', 'L2微观结构-盘口深度', '', '', 'microstructure', 'QuantDB L2/衍生特征 (2023-2026 快照回填)'),
    ('micro_depth_ratio_10', 'L2微观结构-盘口深度', '', '', 'microstructure', 'QuantDB L2/衍生特征 (2023-2026 快照回填)'),
    ('micro_depth_ratio_5', 'L2微观结构-盘口深度', '', '', 'microstructure', 'QuantDB L2/衍生特征 (2023-2026 快照回填)'),
    ('micro_depth_recovery', 'L2微观结构-盘口深度', '', '', 'microstructure', 'QuantDB L2/衍生特征 (2023-2026 快照回填)'),
    ('micro_depth_volatility', 'L2微观结构-盘口深度', '', '', 'microstructure', 'QuantDB L2/衍生特征 (2023-2026 快照回填)'),
    ('micro_depth_weighted_ask', 'L2微观结构-盘口深度', '', '', 'microstructure', 'QuantDB L2/衍生特征 (2023-2026 快照回填)'),
    ('micro_depth_weighted_bid', 'L2微观结构-盘口深度', '', '', 'microstructure', 'QuantDB L2/衍生特征 (2023-2026 快照回填)'),
    ('micro_impact_decay_half_life', 'L2微观结构-价格冲击', '', '', 'microstructure', 'QuantDB L2/衍生特征 (2023-2026 快照回填)'),
    ('micro_impact_permanent_ratio', 'L2微观结构-价格冲击', '', '', 'microstructure', 'QuantDB L2/衍生特征 (2023-2026 快照回填)'),
    ('micro_information_share', 'L2微观结构-信息份额', '', '', 'microstructure', 'QuantDB L2/衍生特征 (2023-2026 快照回填)'),
    ('micro_jump_cluster', 'L2微观结构-价格跳变', '', '', 'microstructure', 'QuantDB L2/衍生特征 (2023-2026 快照回填)'),
    ('micro_jump_count_05pct', 'L2微观结构-价格跳变', '', '', 'microstructure', 'QuantDB L2/衍生特征 (2023-2026 快照回填)'),
    ('micro_jump_recovery_time', 'L2微观结构-价格跳变', '', '', 'microstructure', 'QuantDB L2/衍生特征 (2023-2026 快照回填)'),
    ('micro_jump_size_max', 'L2微观结构-价格跳变', '', '', 'microstructure', 'QuantDB L2/衍生特征 (2023-2026 快照回填)'),
    ('micro_jump_size_mean', 'L2微观结构-价格跳变', '', '', 'microstructure', 'QuantDB L2/衍生特征 (2023-2026 快照回填)'),
    ('micro_jump_skew', 'L2微观结构-价格跳变', '', '', 'microstructure', 'QuantDB L2/衍生特征 (2023-2026 快照回填)'),
    ('micro_liquidity_amihud_20', 'L2微观结构-微观流动性', '', '', 'microstructure', 'QuantDB L2/衍生特征 (2023-2026 快照回填)'),
    ('micro_liquidity_amihud_5', 'L2微观结构-微观流动性', '', '', 'microstructure', 'QuantDB L2/衍生特征 (2023-2026 快照回填)'),
    ('micro_liquidity_close', 'L2微观结构-微观流动性', '', '', 'microstructure', 'QuantDB L2/衍生特征 (2023-2026 快照回填)'),
    ('micro_liquidity_concentration', 'L2微观结构-微观流动性', '', '', 'microstructure', 'QuantDB L2/衍生特征 (2023-2026 快照回填)'),
    ('micro_liquidity_cost', 'L2微观结构-微观流动性', '', '', 'microstructure', 'QuantDB L2/衍生特征 (2023-2026 快照回填)'),
    ('micro_liquidity_daily_pattern', 'L2微观结构-微观流动性', '', '', 'microstructure', 'QuantDB L2/衍生特征 (2023-2026 快照回填)'),
    ('micro_liquidity_extreme', 'L2微观结构-微观流动性', '', '', 'microstructure', 'QuantDB L2/衍生特征 (2023-2026 快照回填)'),
    ('micro_liquidity_holden', 'L2微观结构-微观流动性', '', '', 'microstructure', 'QuantDB L2/衍生特征 (2023-2026 快照回填)'),
    ('micro_liquidity_mining', 'L2微观结构-微观流动性', '', '', 'microstructure', 'QuantDB L2/衍生特征 (2023-2026 快照回填)'),
    ('micro_liquidity_ratio', 'L2微观结构-微观流动性', '', '', 'microstructure', 'QuantDB L2/衍生特征 (2023-2026 快照回填)'),
    ('micro_liquidity_relative_spread', 'L2微观结构-微观流动性', '', '', 'microstructure', 'QuantDB L2/衍生特征 (2023-2026 快照回填)'),
    ('micro_liquidity_roll', 'L2微观结构-微观流动性', '', '', 'microstructure', 'QuantDB L2/衍生特征 (2023-2026 快照回填)'),
    ('micro_liquidity_turnover_decay', 'L2微观结构-微观流动性', '', '', 'microstructure', 'QuantDB L2/衍生特征 (2023-2026 快照回填)'),
    ('micro_liquidity_twa', 'L2微观结构-微观流动性', '', '', 'microstructure', 'QuantDB L2/衍生特征 (2023-2026 快照回填)'),
    ('micro_liquidity_volatility', 'L2微观结构-微观流动性', '', '', 'microstructure', 'QuantDB L2/衍生特征 (2023-2026 快照回填)'),
    ('micro_liquidity_volume_depth_ratio', 'L2微观结构-微观流动性', '', '', 'microstructure', 'QuantDB L2/衍生特征 (2023-2026 快照回填)'),
    ('micro_lunch_break_gap', 'L2微观结构-午休跳空', '', '', 'microstructure', 'QuantDB L2/衍生特征 (2023-2026 快照回填)'),
    ('micro_order_imbalance_tox', 'L2微观结构-订单不平衡', '', '', 'microstructure', 'QuantDB L2/衍生特征 (2023-2026 快照回填)'),
    ('micro_price_discovery', 'L2微观结构-价格发现', '', '', 'microstructure', 'QuantDB L2/衍生特征 (2023-2026 快照回填)'),
    ('micro_realized_spread', 'L2微观结构因子', '', '', 'microstructure', 'QuantDB L2/衍生特征 (2023-2026 快照回填)'),
    ('micro_spread_U_shape', 'L2微观结构-买卖价差', '', '', 'microstructure', 'QuantDB L2/衍生特征 (2023-2026 快照回填)'),
    ('micro_spread_close', 'L2微观结构-买卖价差', '', '', 'microstructure', 'QuantDB L2/衍生特征 (2023-2026 快照回填)'),
    ('micro_spread_decomposition', 'L2微观结构-买卖价差', '', '', 'microstructure', 'QuantDB L2/衍生特征 (2023-2026 快照回填)'),
    ('micro_spread_mid', 'L2微观结构-买卖价差', '', '', 'microstructure', 'QuantDB L2/衍生特征 (2023-2026 快照回填)'),
    ('micro_spread_open', 'L2微观结构-买卖价差', '', '', 'microstructure', 'QuantDB L2/衍生特征 (2023-2026 快照回填)'),
    ('micro_spread_recovery', 'L2微观结构-买卖价差', '', '', 'microstructure', 'QuantDB L2/衍生特征 (2023-2026 快照回填)'),
    ('micro_spread_slope_1_10', 'L2微观结构-买卖价差', '', '', 'microstructure', 'QuantDB L2/衍生特征 (2023-2026 快照回填)'),
    ('micro_spread_slope_5_10', 'L2微观结构-买卖价差', '', '', 'microstructure', 'QuantDB L2/衍生特征 (2023-2026 快照回填)'),
    ('micro_spread_vol_ratio', 'L2微观结构-买卖价差', '', '', 'microstructure', 'QuantDB L2/衍生特征 (2023-2026 快照回填)'),
    ('micro_toxicity_asymmetry', 'L2微观结构-订单流毒性', '', '', 'microstructure', 'QuantDB L2/衍生特征 (2023-2026 快照回填)'),
    ('micro_toxicity_persistence', 'L2微观结构-订单流毒性', '', '', 'microstructure', 'QuantDB L2/衍生特征 (2023-2026 快照回填)'),
    ('micro_trade_arrival_rate', 'L2微观结构-成交序列', '', '', 'microstructure', 'QuantDB L2/衍生特征 (2023-2026 快照回填)'),
    ('micro_trade_continuation', 'L2微观结构-成交序列', '', '', 'microstructure', 'QuantDB L2/衍生特征 (2023-2026 快照回填)'),
    ('micro_trade_interval_cv', 'L2微观结构-成交序列', '', '', 'microstructure', 'QuantDB L2/衍生特征 (2023-2026 快照回填)'),
    ('micro_trade_interval_mean', 'L2微观结构-成交序列', '', '', 'microstructure', 'QuantDB L2/衍生特征 (2023-2026 快照回填)'),
    ('micro_trade_interval_median', 'L2微观结构-成交序列', '', '', 'microstructure', 'QuantDB L2/衍生特征 (2023-2026 快照回填)'),
    ('micro_trade_run_length', 'L2微观结构-成交序列', '', '', 'microstructure', 'QuantDB L2/衍生特征 (2023-2026 快照回填)'),
    ('micro_trade_seq_entropy', 'L2微观结构-成交序列', '', '', 'microstructure', 'QuantDB L2/衍生特征 (2023-2026 快照回填)'),
    ('micro_trade_sign_autocorr', 'L2微观结构-成交序列', '', '', 'microstructure', 'QuantDB L2/衍生特征 (2023-2026 快照回填)'),
    ('micro_trade_sign_transition_BB', 'L2微观结构-成交序列', '', '', 'microstructure', 'QuantDB L2/衍生特征 (2023-2026 快照回填)'),
    ('micro_trade_sign_transition_EB', 'L2微观结构-成交序列', '', '', 'microstructure', 'QuantDB L2/衍生特征 (2023-2026 快照回填)'),
    ('micro_trade_zero_interval_ratio', 'L2微观结构-成交序列', '', '', 'microstructure', 'QuantDB L2/衍生特征 (2023-2026 快照回填)'),
    ('micro_volume_sync', 'L2微观结构-量价同步', '', '', 'microstructure', 'QuantDB L2/衍生特征 (2023-2026 快照回填)'),
    ('micro_vpin_100', 'L2微观结构-VPIN 毒性', '', '', 'microstructure', 'QuantDB L2/衍生特征 (2023-2026 快照回填)'),
    ('micro_vpin_amount_ratio', 'L2微观结构-VPIN 毒性', '', '', 'microstructure', 'QuantDB L2/衍生特征 (2023-2026 快照回填)'),
    ('micro_vpin_bayesian', 'L2微观结构-VPIN 毒性', '', '', 'microstructure', 'QuantDB L2/衍生特征 (2023-2026 快照回填)'),
    ('micro_vpin_conviction', 'L2微观结构-VPIN 毒性', '', '', 'microstructure', 'QuantDB L2/衍生特征 (2023-2026 快照回填)'),
    ('micro_vpin_entropy', 'L2微观结构-VPIN 毒性', '', '', 'microstructure', 'QuantDB L2/衍生特征 (2023-2026 快照回填)'),
    ('micro_vpin_hurst', 'L2微观结构-VPIN 毒性', '', '', 'microstructure', 'QuantDB L2/衍生特征 (2023-2026 快照回填)'),
    ('micro_vpin_kyle', 'L2微观结构-VPIN 毒性', '', '', 'microstructure', 'QuantDB L2/衍生特征 (2023-2026 快照回填)'),
    ('micro_vpin_quantile_ratio', 'L2微观结构-VPIN 毒性', '', '', 'microstructure', 'QuantDB L2/衍生特征 (2023-2026 快照回填)'),
    ('micro_vpin_surge', 'L2微观结构-VPIN 毒性', '', '', 'microstructure', 'QuantDB L2/衍生特征 (2023-2026 快照回填)'),
    ('micro_vpin_tail_risk', 'L2微观结构-VPIN 毒性', '', '', 'microstructure', 'QuantDB L2/衍生特征 (2023-2026 快照回填)'),
    ('micro_vpin_trend', 'L2微观结构-VPIN 毒性', '', '', 'microstructure', 'QuantDB L2/衍生特征 (2023-2026 快照回填)'),
    ('micro_vpin_vol_ratio', 'L2微观结构-VPIN 毒性', '', '', 'microstructure', 'QuantDB L2/衍生特征 (2023-2026 快照回填)'),
    ('micro_vpin_zscore_20', 'L2微观结构-VPIN 毒性', '', '', 'microstructure', 'QuantDB L2/衍生特征 (2023-2026 快照回填)'),
    ('micro_zone_distribution', 'L2微观结构-日内时段分布', '', '', 'microstructure', 'QuantDB L2/衍生特征 (2023-2026 快照回填)'),
    ('micro_zone_imbalance_am', 'L2微观结构-日内时段分布', '', '', 'microstructure', 'QuantDB L2/衍生特征 (2023-2026 快照回填)'),
    ('micro_zone_imbalance_pm', 'L2微观结构-日内时段分布', '', '', 'microstructure', 'QuantDB L2/衍生特征 (2023-2026 快照回填)'),
    ('micro_zone_morning_evening_ratio', 'L2微观结构-日内时段分布', '', '', 'microstructure', 'QuantDB L2/衍生特征 (2023-2026 快照回填)'),
    ('micro_zone_rv_ratio_AM', 'L2微观结构-日内时段分布', '', '', 'microstructure', 'QuantDB L2/衍生特征 (2023-2026 快照回填)'),
    ('micro_zone_rv_ratio_PM', 'L2微观结构-日内时段分布', '', '', 'microstructure', 'QuantDB L2/衍生特征 (2023-2026 快照回填)'),
    ('micro_zone_rv_ratio_close', 'L2微观结构-日内时段分布', '', '', 'microstructure', 'QuantDB L2/衍生特征 (2023-2026 快照回填)'),
    ('micro_zone_rv_ratio_open', 'L2微观结构-日内时段分布', '', '', 'microstructure', 'QuantDB L2/衍生特征 (2023-2026 快照回填)'),
    ('micro_zone_spread_ratio_close', 'L2微观结构-日内时段分布', '', '', 'microstructure', 'QuantDB L2/衍生特征 (2023-2026 快照回填)'),
    ('micro_zone_spread_ratio_mid', 'L2微观结构-日内时段分布', '', '', 'microstructure', 'QuantDB L2/衍生特征 (2023-2026 快照回填)'),
    ('micro_zone_spread_ratio_open', 'L2微观结构-日内时段分布', '', '', 'microstructure', 'QuantDB L2/衍生特征 (2023-2026 快照回填)'),
    ('micro_zone_vol_ratio_T1', 'L2微观结构-日内时段分布', '', '', 'microstructure', 'QuantDB L2/衍生特征 (2023-2026 快照回填)'),
    ('micro_zone_vol_ratio_T2', 'L2微观结构-日内时段分布', '', '', 'microstructure', 'QuantDB L2/衍生特征 (2023-2026 快照回填)'),
    ('micro_zone_vol_ratio_T3', 'L2微观结构-日内时段分布', '', '', 'microstructure', 'QuantDB L2/衍生特征 (2023-2026 快照回填)'),
    ('micro_zone_vol_ratio_T4', 'L2微观结构-日内时段分布', '', '', 'microstructure', 'QuantDB L2/衍生特征 (2023-2026 快照回填)'),
    ('micro_zone_vol_ratio_T5', 'L2微观结构-日内时段分布', '', '', 'microstructure', 'QuantDB L2/衍生特征 (2023-2026 快照回填)'),
    ('micro_zone_vol_ratio_T6', 'L2微观结构-日内时段分布', '', '', 'microstructure', 'QuantDB L2/衍生特征 (2023-2026 快照回填)'),
    ('micro_zone_vol_ratio_T7', 'L2微观结构-日内时段分布', '', '', 'microstructure', 'QuantDB L2/衍生特征 (2023-2026 快照回填)'),
    ('micro_zone_vol_ratio_T8', 'L2微观结构-日内时段分布', '', '', 'microstructure', 'QuantDB L2/衍生特征 (2023-2026 快照回填)'),
    ('micro_zone_vpin_open', 'L2微观结构-日内时段分布', '', '', 'microstructure', 'QuantDB L2/衍生特征 (2023-2026 快照回填)'),
    ('gtja_016', 'GTJA Alpha16: -TSMAX(RANK(CORR(rank(vol),rank(vwap),5)),5)', '', 'GTJA Alpha16: -TSMAX(RANK(CORR(rank(vol),rank(vwap),5)),5)', 'gtja', 'GTJA Alpha191 (国泰君安) — feature_snapshots/model_features_*.parquet'),
    ('gtja_032', 'GTJA Alpha32: -SUM(RANK(CORR(rank(high),rank(vol),3)),3)', '', 'GTJA Alpha32: -SUM(RANK(CORR(rank(high),rank(vol),3)),3)', 'gtja', 'GTJA Alpha191 (国泰君安) — feature_snapshots/model_features_*.parquet'),
    ('gtja_062', 'GTJA Alpha62: -CORR(high, rank(vol), 5)', '', 'GTJA Alpha62: -CORR(high, rank(vol), 5)', 'gtja', 'GTJA Alpha191 (国泰君安) — feature_snapshots/model_features_*.parquet'),
    ('gtja_083', 'GTJA Alpha83: -RANK(COV(rank(high), rank(vol), 5))', '', 'GTJA Alpha83: -RANK(COV(rank(high), rank(vol), 5))', 'gtja', 'GTJA Alpha191 (国泰君安) — feature_snapshots/model_features_*.parquet'),
    ('gtja_090', 'GTJA Alpha90: -RANK(CORR(rank(vwap), rank(vol), 5))', '', 'GTJA Alpha90: -RANK(CORR(rank(vwap), rank(vol), 5))', 'gtja', 'GTJA Alpha191 (国泰君安) — feature_snapshots/model_features_*.parquet'),
    ('gtja_099', 'GTJA Alpha99: -RANK(COV(rank(close), rank(vol), 5))', '', 'GTJA Alpha99: -RANK(COV(rank(close), rank(vol), 5))', 'gtja', 'GTJA Alpha191 (国泰君安) — feature_snapshots/model_features_*.parquet'),
    ('gtja_036', 'GTJA Alpha36: RANK(SUM(CORR(rank(vol),rank(vwap),6),2))', '', 'GTJA Alpha36: RANK(SUM(CORR(rank(vol),rank(vwap),6),2))', 'gtja', 'GTJA Alpha191 (国泰君安) — feature_snapshots/model_features_*.parquet'),
    ('gtja_070', 'GTJA Alpha70: STD(AMOUNT, 6)', '', 'GTJA Alpha70: STD(AMOUNT, 6)', 'gtja', 'GTJA Alpha191 (国泰君安) — feature_snapshots/model_features_*.parquet'),
    ('gtja_074', 'GTJA Alpha74: RANK(CORR(SUM(price,20),SUM(MA(vol,40),20),7))+...', '', 'GTJA Alpha74: RANK(CORR(SUM(price,20),SUM(MA(vol,40),20),7))+...', 'gtja', 'GTJA Alpha191 (国泰君安) — feature_snapshots/model_features_*.parquet'),
    ('gtja_150', 'GTJA Alpha150: (close+high+low)/3 * volume', '', 'GTJA Alpha150: (close+high+low)/3 * volume', 'gtja', 'GTJA Alpha191 (国泰君安) — feature_snapshots/model_features_*.parquet'),
    ('gtja_176', 'GTJA Alpha176: CORR(rank(KDJ_RSV_12), rank(vol), 6)', '', 'GTJA Alpha176: CORR(rank(KDJ_RSV_12), rank(vol), 6)', 'gtja', 'GTJA Alpha191 (国泰君安) — feature_snapshots/model_features_*.parquet'),
    ('gtja_179', 'GTJA Alpha179: RANK(CORR(vwap,vol,4))*RANK(CORR(rank(low),rank(MA(vol,50)),12))', '', 'GTJA Alpha179: RANK(CORR(vwap,vol,4))*RANK(CORR(rank(low),rank(MA(vol,50)),12))', 'gtja', 'GTJA Alpha191 (国泰君安) — feature_snapshots/model_features_*.parquet'),
    ('gtja_042', 'GTJA Alpha42: -RANK(STD(high,10)) * CORR(high,vol,10)', '', 'GTJA Alpha42: -RANK(STD(high,10)) * CORR(high,vol,10)', 'gtja', 'GTJA Alpha191 (国泰君安) — feature_snapshots/model_features_*.parquet'),
    ('gtja_095', 'GTJA Alpha95: STD(AMOUNT, 20)', '', 'GTJA Alpha95: STD(AMOUNT, 20)', 'gtja', 'GTJA Alpha191 (国泰君安) — feature_snapshots/model_features_*.parquet'),
    ('gtja_158', 'GTJA Alpha158: (high-low)/close (基于 EMA(close,15) 推导)', '', 'GTJA Alpha158: (high-low)/close (基于 EMA(close,15) 推导)', 'gtja', 'GTJA Alpha191 (国泰君安) — feature_snapshots/model_features_*.parquet'),
    ('gtja_159', 'GTJA Alpha159: 多周期 RSV 加权（牛熊反转因子）', '', 'GTJA Alpha159: 多周期 RSV 加权（牛熊反转因子）', 'gtja', 'GTJA Alpha191 (国泰君安) — feature_snapshots/model_features_*.parquet'),
    ('chip_profit_ratio_20', '20日获利比例', '', '', 'chip', 'l1_factors'),
    ('chip_profit_ratio_60', '60日获利比例', '', '', 'chip', 'l1_factors'),
    ('chip_profit_ratio_120', '120日获利比例', '', '', 'chip', 'l1_factors'),
    ('chip_concentration_20', '20日筹码集中度', '筹码成本分布90%区间宽度/现价。数值越小筹码越集中', '', 'chip', 'l1_factors'),
    ('chip_peak_distance', '筹码峰距离', '', '', 'chip', 'l1_factors'),
    ('chip_floating_ratio', '浮动筹码比例', '', '', 'chip', 'l1_factors'),
    ('chip_cost_90_width', '90%筹码宽度', '筹码成本分布P95-P5的区间宽度（元）', '', 'chip', 'l1_factors'),
    ('chip_profit_delta_5', '5日获利变化', '', '', 'chip', 'l1_factors'),
    ('concept_hot_score', '概念热度评分', '', '', 'concept', 'l1_factors'),
    ('concept_momentum_top3', '概念动量Top3', '', '', 'concept', 'l1_factors'),
    ('concept_exposure_top1', '概念暴露度Top1', '', '', 'concept', 'l1_factors'),
    ('concept_rotation_score', '概念轮动评分', '', '', 'concept', 'l1_factors'),
    ('concept_crowding_max', '概念拥挤度最大值', '', '', 'concept', 'l1_factors'),
    ('concept_diversity', '概念分散度', '', '', 'concept', 'l1_factors'),
    ('concept_flow_rank', '概念资金流排名', '', '', 'concept', 'l1_factors'),
    ('concept_leader_score', '概念龙头评分', '', '', 'concept', 'l1_factors'),
    ('concept_cross_sector', '跨板块概念数', '', '', 'concept', 'l1_factors'),
    ('concept_volume_ratio', '概念量比', '', '', 'concept', 'l1_factors'),
    ('tech_bb_width', '布林带宽度', '布林带上下轨距离，衡量波动区间', '', 'technical', 'l1_factors'),
    ('tech_bb_pos', '布林带位置', '收盘价在布林带中的相对位置（0=下轨，1=上轨）', '', 'technical', 'l1_factors'),
    ('tech_cci_20', 'CCI(20)', '顺势指标。大于100超买，小于-100超卖', '', 'technical', 'l1_factors'),
    ('tech_adx_14', 'ADX(14)', '平均趋向指数，衡量趋势强度（大于25为强趋势）', '', 'technical', 'l1_factors'),
    ('tech_vol_price_corr_20', '量价相关性20日', '', '', 'technical', 'l1_factors'),
    ('rsi_6', 'RSI(6)', '', 'RSI(close, 6)', 'technical', 'features_daily / technical_indicators'),
    ('macd_hist', 'MACD柱值', '', 'MACD(close, 12, 26, 9).hist', 'technical', 'features_daily / technical_indicators'),
    ('kdj_d', 'KDJ-D', '', 'KDJ(close, high, low, 9, 3, 3).d', 'technical', 'features_daily / technical_indicators'),
    ('amount', '成交额（元）', '', '', 'technical', 'QuantDB L2/衍生特征 (2023-2026 快照回填)'),
    ('kdj_j', 'KDJ 指标 K/J 线', '', '', 'technical', 'QuantDB L2/衍生特征 (2023-2026 快照回填)'),
    ('kdj_k', 'KDJ 指标 K/J 线', '', '', 'technical', 'QuantDB L2/衍生特征 (2023-2026 快照回填)'),
    ('ma10', 'N日均线（后复权）', '', '', 'technical', 'QuantDB L2/衍生特征 (2023-2026 快照回填)'),
    ('ma20', 'N日均线（后复权）', '', '', 'technical', 'QuantDB L2/衍生特征 (2023-2026 快照回填)'),
    ('ma5', 'N日均线（后复权）', '', '', 'technical', 'QuantDB L2/衍生特征 (2023-2026 快照回填)'),
    ('ma60', 'N日均线（后复权）', '', '', 'technical', 'QuantDB L2/衍生特征 (2023-2026 快照回填)'),
    ('ma_gap_10', '收盘价相对N日均线的乖离', '', '', 'technical', 'QuantDB L2/衍生特征 (2023-2026 快照回填)'),
    ('ma_gap_20', '收盘价相对N日均线的乖离', '', '', 'technical', 'QuantDB L2/衍生特征 (2023-2026 快照回填)'),
    ('ma_gap_5', '收盘价相对N日均线的乖离', '', '', 'technical', 'QuantDB L2/衍生特征 (2023-2026 快照回填)'),
    ('macd_dea', 'MACD DIF/DEA', '', '', 'technical', 'QuantDB L2/衍生特征 (2023-2026 快照回填)'),
    ('macd_dif', 'MACD DIF/DEA', '', '', 'technical', 'QuantDB L2/衍生特征 (2023-2026 快照回填)'),
    ('mfi_14', '14日资金流量指标 MFI', '基于典型价格与成交量的资金流强弱指标', '', 'technical', 'QuantDB L2/衍生特征 (2023-2026 快照回填)'),
    ('obv_slope_20', '20日 OBV 斜率', '能量潮指标近20日趋势斜率', '', 'technical', 'QuantDB L2/衍生特征 (2023-2026 快照回填)'),
    ('pct_change', '日涨跌幅', '', '', 'technical', 'QuantDB L2/衍生特征 (2023-2026 快照回填)'),
    ('rsi_14', '14日 RSI', '', '', 'technical', 'QuantDB L2/衍生特征 (2023-2026 快照回填)'),
    ('tech_close_to_high_20', '收盘价距20日新高的位置', '收盘价相对20日最高价的位置', '', 'technical', 'QuantDB L2/衍生特征 (2023-2026 快照回填)'),
    ('tech_max_drawdown_20', '20日最大回撤', '近20日价格路径的最大回撤幅度', '', 'technical', 'QuantDB L2/衍生特征 (2023-2026 快照回填)'),
    ('vol_weighted_price', '成交量加权均价 VWAP', '收盘价相对成交量加权平均价的偏离', '', 'technical', 'QuantDB L2/衍生特征 (2023-2026 快照回填)'),
    ('fun_turnover_1', '1日换手率', '当日换手率（旧版 L1 命名）', '', 'fundamental', 'l1_factors'),
    ('fun_turnover_5', '5日换手率', '近5日换手率均值（旧版 L1 命名）', '', 'fundamental', 'l1_factors'),
    ('fun_turnover_20', '20日换手率', '近20日换手率均值（旧版 L1 命名）', '', 'fundamental', 'l1_factors'),
    ('fun_mv', '市值', '市值取对数口径（旧版 L1 命名，同 fun_float_mv）', '', 'fundamental', 'l1_factors'),
    ('fun_total_mv', '总市值', 'ln(不复权收盘价×总股本)。使用时需 exp() 还原为元', '', 'fundamental', 'l1_factors'),
    ('fun_pe', 'PE', '总市值/净利润TTM，倍数', '', 'fundamental', 'l1_factors'),
    ('fun_pb', 'PB', '总市值/净资产，倍数', '', 'fundamental', 'l1_factors'),
    ('fun_bp', 'BP', '1/市净率。价值因子，越高越偏价值', '', 'fundamental', 'l1_factors'),
    ('fun_ep', 'EP', '净利润TTM/总市值。市盈率的倒数', '', 'fundamental', 'l1_factors'),
    ('fun_mv_rank', '市值排名', '流通市值的当日全市场百分位（0~1），规模因子代表', '', 'fundamental', 'l1_factors'),
    ('fun_value_zscore', '价值Z-Score', '(E/P与B/P各自截面Z分数的均值)。综合估值，越高越便宜', '', 'fundamental', 'l1_factors'),
    ('fun_roe', 'ROE', '净利润TTM/净资产×100。百分数值（11.76=11.76%）', '', 'fundamental', 'l1_factors'),
    ('fun_peg', 'PEG', '市盈率/净利润增长率。小于1常被视为成长性未被充分定价', '', 'fundamental', 'l1_factors'),
    ('dividend_rate', '股息率', '', 'dividend / close', 'fundamental', 'valuation'),
    ('ps_ttm', '市销率(TTM): 总市值/营业收入TTM', '', 'total_mv / revenue_ttm', 'fundamental', 'feature_snapshots/model_features_*.parquet'),
    ('annual_net_profit', '年度净利润', '', '', 'fundamental', 'QuantDB L2/衍生特征 (2023-2026 快照回填)'),
    ('circulating_capital', '流通股本', '', '', 'fundamental', 'QuantDB L2/衍生特征 (2023-2026 快照回填)'),
    ('equity', '净资产', '', '', 'fundamental', 'QuantDB L2/衍生特征 (2023-2026 快照回填)'),
    ('float_mv', '流通市值', '', '', 'fundamental', 'QuantDB L2/衍生特征 (2023-2026 快照回填)'),
    ('fun_float_mv', '财务指标（流通市值/净利润增速）', 'ln(不复权收盘价×流通股本)。衡量规模，使用时需 exp() 还原', '', 'fundamental', 'QuantDB L2/衍生特征 (2023-2026 快照回填)'),
    ('fun_np_growth', '财务指标（流通市值/净利润增速）', '净利润同比增长速度', '', 'fundamental', 'QuantDB L2/衍生特征 (2023-2026 快照回填)'),
    ('net_profit_ttm', '净利润 TTM', '', '', 'fundamental', 'QuantDB L2/衍生特征 (2023-2026 快照回填)'),
    ('pb', '市净率', '', '', 'fundamental', 'QuantDB L2/衍生特征 (2023-2026 快照回填)'),
    ('pe_static', '市盈率 TTM/静态', '', '', 'fundamental', 'QuantDB L2/衍生特征 (2023-2026 快照回填)'),
    ('pe_ttm', '市盈率 TTM/静态', '', '', 'fundamental', 'QuantDB L2/衍生特征 (2023-2026 快照回填)'),
    ('revenue_ttm', '营业收入 TTM', '', '', 'fundamental', 'QuantDB L2/衍生特征 (2023-2026 快照回填)'),
    ('total_capital', '总股本', '', '', 'fundamental', 'QuantDB L2/衍生特征 (2023-2026 快照回填)'),
    ('total_mv', '总市值', '', '', 'fundamental', 'QuantDB L2/衍生特征 (2023-2026 快照回填)'),
    ('ca_n_pis', 'Top50参与人数量（少=筹码集中，负向）', 'CCASS Top50 参与人数量（少=筹码集中，负向）', 'CCASS Top50 参与人数量', 'holding', 'ccass_factors 日频分区'),
    ('ca_hhi_disc', '披露内份额HHI集中度（正向）', 'Top50 披露份额赫芬达尔指数，越高筹码越集中', 'ca_hhi_disc', 'holding', 'ccass_factors 日频分区'),
    ('ca_rank_overlap_20d', 'Top50名次20日重叠率（稳定=长线布局）', '参与人名单与 20 个交易日前的 Jaccard 重叠率', 'ca_rank_overlap_20d', 'holding', 'ccass_factors 日频分区'),
    ('ca_broker_pct', '券商散户线占比（负向）', '券商类参与人披露份额合计', 'ca_broker_pct', 'holding', 'ccass_factors 日频分区'),
    ('ca_disclosed_sum', '披露覆盖度（负向）', 'Top50 参与人披露比例合计（衡量披露质量）', 'ca_disclosed_sum', 'holding', 'ccass_factors 日频分区'),
    ('ca_cust_share_disc', '大行托管占披露比（外资线，正向）', '托管行类参与人占披露份额比例', 'ca_cust_share_disc', 'holding', 'ccass_factors 日频分区'),
    ('ca_south_pct', '南向(中国结算双席位)持股占比（负向）', '港股通席位（A00003/A00004）披露份额合计', 'ca_south_pct', 'holding', 'ccass_factors 日频分区'),
    ('sb_quantity', '南向持股数量（正向）', '港股通持股数量（正向）', 'sb_quantity', 'holding', 'south_factors 日频分区'),
    ('custom_ret_1d', '自定义1日涨跌幅', '当日收盘价相对前收的涨跌幅，演示用（OHLCV直接计算）', '(close / pre_close) - 1', 'custom', 'OHLCV演示'),
    ('custom_amp_1d', '自定义1日振幅', '当日最高最低价相对前收的振幅，演示用', '(high - low) / pre_close', 'custom', 'OHLCV演示'),
    ('custom_close_pos', '自定义收盘位置', '收盘价在当日最高最低区间中的相对位置（0=最低，1=最高），演示用', '(close - low) / (high - low)', 'custom', 'OHLCV演示'),
    ('custom_vol_ratio_5', '自定义5日量比', '当日成交量与近5日均量的比值，演示用', 'volume / mean(volume, 5)', 'custom', 'OHLCV演示'),
    ('custom_amt_ma_5', '自定义5日成交额均线', '近5日成交额均值，衡量短期资金活跃度，演示用', 'mean(amount, 5)', 'custom', 'OHLCV演示')
ON CONFLICT (feature_key) DO NOTHING;

-- ---- 4. 版本成员（534 条）----
--   目标版本不存在时整体跳过（避免外键报错）。id 由 SERIAL 自增。
INSERT INTO qm_feature_set_item (version_id, category_id, feature_key, order_no, enabled)
SELECT 'v2.0', v.category_id, v.feature_key, v.order_no, v.enabled
FROM (VALUES
    ('ohlcv', 'open', 2, true),
    ('ohlcv', 'high', 3, true),
    ('ohlcv', 'low', 4, true),
    ('ohlcv', 'close', 1, true),
    ('ohlcv', 'volume', 5, true),
    ('ohlcv', 'factor', 6, true),
    ('momentum', 'mom_ret_1d', 1, true),
    ('momentum', 'mom_ret_3d', 2, true),
    ('momentum', 'mom_ret_5d', 2, true),
    ('momentum', 'mom_ret_10d', 4, true),
    ('momentum', 'mom_ret_20d', 3, true),
    ('momentum', 'mom_ret_60d', 4, true),
    ('momentum', 'mom_ret_120d', 7, true),
    ('momentum', 'mom_ma_gap_5', 5, true),
    ('momentum', 'mom_ma_gap_10', 9, true),
    ('momentum', 'mom_ma_gap_20', 6, true),
    ('momentum', 'mom_ma_gap_60', 7, true),
    ('momentum', 'mom_ma_gap_120', 12, true),
    ('momentum', 'mom_ema_gap_12', 13, true),
    ('momentum', 'mom_ema_gap_26', 14, true),
    ('momentum', 'mom_macd_dif', 15, true),
    ('momentum', 'mom_macd_dea', 16, true),
    ('momentum', 'mom_macd_hist', 8, true),
    ('momentum', 'mom_rsi_6', 18, true),
    ('momentum', 'mom_rsi_14', 9, true),
    ('momentum', 'mom_kdj_k', 10, true),
    ('momentum', 'mom_kdj_d', 21, true),
    ('momentum', 'mom_kdj_j', 22, true),
    ('momentum', 'mom_roc_12', 23, true),
    ('momentum', 'mom_breakout_20d', 11, true),
    ('momentum', 'SUMP20', 24, true),
    ('momentum', 'SUMN20', 25, true),
    ('momentum', 'SUMD20', 26, true),
    ('momentum', 'SUMP30', 27, true),
    ('momentum', 'SUMN30', 28, true),
    ('momentum', 'SUMD30', 29, true),
    ('momentum', 'SUMP60', 30, true),
    ('momentum', 'SUMN60', 31, true),
    ('momentum', 'SUMD60', 32, true),
    ('momentum', 'RANK5', 33, true),
    ('momentum', 'RANK10', 34, true),
    ('momentum', 'RANK20', 35, true),
    ('momentum', 'RANK30', 36, true),
    ('momentum', 'RANK60', 37, true),
    ('volatility', 'vol_std_5', 1, true),
    ('volatility', 'vol_std_10', 2, true),
    ('volatility', 'vol_std_20', 1, true),
    ('volatility', 'vol_std_60', 2, true),
    ('volatility', 'vol_atr_14', 3, true),
    ('volatility', 'vol_atr_20', 6, true),
    ('volatility', 'vol_true_range', 7, true),
    ('volatility', 'vol_parkinson_10', 8, true),
    ('volatility', 'vol_parkinson_20', 4, true),
    ('volatility', 'vol_gk_10', 10, true),
    ('volatility', 'vol_gk_20', 11, true),
    ('volatility', 'vol_rs_10', 12, true),
    ('volatility', 'vol_rs_20', 13, true),
    ('volatility', 'vol_downside_20', 5, true),
    ('volatility', 'vol_upside_20', 6, true),
    ('volatility', 'vol_realized_rv', 7, true),
    ('volatility', 'vol_realized_rrv', 8, true),
    ('volatility', 'vol_realized_rskew', 9, true),
    ('volatility', 'vol_realized_rkurt', 19, true),
    ('volatility', 'vol_jump_zadj', 10, true),
    ('volatility', 'vol_jump_rjv_ratio', 21, true),
    ('volatility', 'vol_jump_sjv_ratio', 22, true),
    ('volatility', 'vol_realized_5min', 23, true),
    ('volatility', 'vol_realized_sjv', 24, true),
    ('volatility', 'vol_realized_jump', 25, true),
    ('volatility', 'vol_skew', 26, true),
    ('volatility', 'vol_kurtosis', 27, true),
    ('volatility', 'vol_persistence', 28, true),
    ('volatility', 'vol_up_down_ratio', 29, true),
    ('volatility', 'MAX5', 30, true),
    ('volatility', 'MIN5', 31, true),
    ('volatility', 'MAX10', 32, true),
    ('volatility', 'MIN10', 33, true),
    ('volatility', 'MAX20', 34, true),
    ('volatility', 'MIN20', 35, true),
    ('volatility', 'MAX30', 36, true),
    ('volatility', 'MIN30', 37, true),
    ('volatility', 'MAX60', 38, true),
    ('volatility', 'MIN60', 39, true),
    ('volatility', 'vol_amp_1', 1001, true),
    ('volatility', 'vol_amp_20', 1002, true),
    ('volatility', 'vol_gini', 1003, true),
    ('volatility', 'vol_large_trade_intensity', 1004, true),
    ('volatility', 'vol_price_corr', 1005, true),
    ('volatility', 'vol_price_divergence', 1006, true),
    ('volatility', 'vol_realized_10min', 1007, true),
    ('volatility', 'vol_realized_15min', 1008, true),
    ('volatility', 'vol_realized_am', 1009, true),
    ('volatility', 'vol_realized_closing', 1010, true),
    ('volatility', 'vol_realized_opening', 1011, true),
    ('volatility', 'vol_realized_pm', 1012, true),
    ('volatility', 'vol_tick_density', 1013, true),
    ('volatility', 'vol_to_ma5', 1014, true),
    ('volatility', 'vol_turnover_am_pm', 1015, true),
    ('volatility', 'vol_turnover_close', 1016, true),
    ('volatility', 'vol_turnover_concentration', 1017, true),
    ('volatility', 'vol_turnover_open', 1018, true),
    ('volatility', 'vol_turnover_total', 1019, true),
    ('liquidity', 'liq_turnover_os', 3, true),
    ('liquidity', 'liq_turnover_tl', 2, true),
    ('liquidity', 'liq_volume', 1, true),
    ('liquidity', 'liq_volume_ma_5', 4, true),
    ('liquidity', 'liq_volume_ma_10', 5, true),
    ('liquidity', 'liq_volume_ma_20', 6, true),
    ('liquidity', 'liq_volume_ratio_5', 4, true),
    ('liquidity', 'liq_volume_ratio_20', 8, true),
    ('liquidity', 'liq_amount', 2, true),
    ('liquidity', 'liq_amount_ma_5', 10, true),
    ('liquidity', 'liq_amount_ma_10', 11, true),
    ('liquidity', 'liq_amount_ma_20', 12, true),
    ('liquidity', 'liq_amount_ratio_5', 13, true),
    ('liquidity', 'liq_amount_ratio_20', 14, true),
    ('liquidity', 'liq_trade_count', 15, false),
    ('liquidity', 'liq_avg_trade_size', 16, false),
    ('liquidity', 'liq_obv_20', 17, true),
    ('liquidity', 'liq_obv_60', 18, true),
    ('liquidity', 'liq_mfi_14', 5, true),
    ('liquidity', 'liq_accdist_20', 20, true),
    ('liquidity', 'liq_amihud_20', 6, true),
    ('liquidity', 'liq_amihud_60', 22, true),
    ('liquidity', 'vol_to_ma20', 10, true),
    ('liquidity', 'volume_ma_3', 11, true),
    ('liquidity', 'volume_trend_3d', 12, true),
    ('liquidity', 'amount_ma_5', 23, true),
    ('liquidity', 'turn_1', 1020, true),
    ('liquidity', 'turn_10', 1021, true),
    ('liquidity', 'turn_20', 1022, true),
    ('liquidity', 'turn_3', 1023, true),
    ('liquidity', 'turn_5', 1024, true),
    ('liquidity', 'turn_60', 1025, true),
    ('liquidity', 'turn_acc_20', 1026, true),
    ('liquidity', 'turn_acc_5', 1027, true),
    ('liquidity', 'turn_breakout_20', 1028, true),
    ('liquidity', 'turn_high_days_10', 1029, true),
    ('liquidity', 'turn_hl_pos_20', 1030, true),
    ('liquidity', 'turn_ratio_1_20', 1031, true),
    ('liquidity', 'turn_ratio_1_5', 1032, true),
    ('liquidity', 'turn_std_20', 1033, true),
    ('liquidity', 'turn_trend_5_20', 1034, true),
    ('liquidity', 'turn_z_20', 1035, true),
    ('fund_flow', 'flow_net_amount', 1, true),
    ('fund_flow', 'flow_net_amount_ratio', 2, true),
    ('fund_flow', 'flow_large_net_amount', 3, true),
    ('fund_flow', 'flow_large_net_ratio', 4, true),
    ('fund_flow', 'flow_medium_net_amount', 5, true),
    ('fund_flow', 'flow_medium_net_ratio', 6, true),
    ('fund_flow', 'flow_small_net_amount', 7, true),
    ('fund_flow', 'flow_small_net_ratio', 8, true),
    ('fund_flow', 'flow_net_order_count', 9, true),
    ('fund_flow', 'flow_net_order_ratio', 10, true),
    ('fund_flow', 'flow_large_net_order', 11, true),
    ('fund_flow', 'flow_large_order_ratio', 12, true),
    ('fund_flow', 'flow_vpin', 4, true),
    ('fund_flow', 'flow_vpin_ma_5', 5, true),
    ('fund_flow', 'flow_vpin_ma_20', 6, true),
    ('fund_flow', 'flow_vpin_delta_5', 16, true),
    ('fund_flow', 'flow_qsp', 17, true),
    ('fund_flow', 'flow_esp', 18, true),
    ('fund_flow', 'flow_aqsp', 19, true),
    ('fund_flow', 'flow_qsp_time', 20, true),
    ('fund_flow', 'flow_esp_time', 21, true),
    ('fund_flow', 'flow_pressure_index', 7, true),
    ('fund_flow', 'flow_net_ratio', 23, true),
    ('fund_flow', 'flow_large_net', 24, true),
    ('fund_flow', 'flow_medium_net', 25, true),
    ('fund_flow', 'flow_small_net', 26, true),
    ('fund_flow', 'flow_super_net', 27, true),
    ('fund_flow', 'flow_large_ratio', 28, true),
    ('fund_flow', 'flow_medium_ratio', 29, true),
    ('fund_flow', 'flow_small_ratio', 30, true),
    ('fund_flow', 'flow_imbalance_volume', 31, true),
    ('fund_flow', 'flow_consistency', 32, true),
    ('fund_flow', 'flow_money_flow_index', 33, true),
    ('fund_flow', 'flow_big_trade_ratio', 34, true),
    ('fund_flow', 'micro_vpin_8', 35, true),
    ('fund_flow', 'micro_vpin_20', 36, true),
    ('fund_flow', 'micro_vpin_50', 37, true),
    ('fund_flow', 'micro_vpin_ma_5', 38, true),
    ('fund_flow', 'micro_vpin_ma_20', 39, true),
    ('fund_flow', 'micro_vpin_delta_5', 40, true),
    ('fund_flow', 'micro_pin', 41, true),
    ('fund_flow', 'amt_close_pos', 1036, true),
    ('fund_flow', 'amt_high_days_10', 1037, true),
    ('fund_flow', 'amt_log', 1038, true),
    ('fund_flow', 'amt_ma_20', 1039, true),
    ('fund_flow', 'amt_ma_5', 1040, true),
    ('fund_flow', 'amt_ma_60', 1041, true),
    ('fund_flow', 'amt_net_flow_20', 1042, true),
    ('fund_flow', 'amt_net_flow_5', 1043, true),
    ('fund_flow', 'amt_ratio_1_20', 1044, true),
    ('fund_flow', 'amt_ratio_1_5', 1045, true),
    ('fund_flow', 'amt_ratio_5_20', 1046, true),
    ('fund_flow', 'amt_skew_20', 1047, true),
    ('fund_flow', 'amt_up_ratio_20', 1048, true),
    ('fund_flow', 'amt_up_ratio_5', 1049, true),
    ('fund_flow', 'amt_vol_ratio_20', 1050, true),
    ('fund_flow', 'amt_z_20', 1051, true),
    ('fund_flow', 'flow_buy_amount', 1052, true),
    ('fund_flow', 'flow_buy_ratio', 1053, true),
    ('fund_flow', 'flow_sell_amount', 1054, true),
    ('fund_flow', 'flow_sell_ratio', 1055, true),
    ('fund_flow', 'flow_super_ratio', 1056, true),
    ('style', 'style_ln_mv_total', 1, true),
    ('style', 'style_ln_mv_float', 2, true),
    ('style', 'style_bp', 7, true),
    ('style', 'style_ep_ttm', 8, true),
    ('style', 'style_smb', 5, true),
    ('style', 'style_hml', 6, true),
    ('style', 'style_mkt_premium', 7, true),
    ('style', 'style_beta_20', 3, true),
    ('style', 'style_beta_60', 4, true),
    ('style', 'style_beta_120', 10, true),
    ('style', 'style_idio_vol_20', 5, true),
    ('style', 'style_idio_vol_60', 12, true),
    ('style', 'style_residual_ret_20', 6, true),
    ('style', 'style_valuation_composite', 14, false),
    ('style', 'style_size_percentile', 15, true),
    ('style', 'style_value_percentile', 16, false),
    ('style', 'style_size_20', 17, true),
    ('style', 'style_value_20', 18, true),
    ('style', 'beta_20', 1057, true),
    ('industry', 'ind_ret_1d', 1, true),
    ('industry', 'ind_ret_5d', 2, true),
    ('industry', 'ind_ret_10d', 3, true),
    ('industry', 'ind_ret_20d', 2, true),
    ('industry', 'ind_vol_20', 5, true),
    ('industry', 'ind_turnover_20', 6, true),
    ('industry', 'ind_amount_20', 7, true),
    ('industry', 'ind_strength_20', 3, true),
    ('industry', 'ind_strength_60', 9, true),
    ('industry', 'ind_dispersion_20', 10, true),
    ('industry', 'ind_up_breadth_20', 11, true),
    ('industry', 'ind_down_breadth_20', 12, true),
    ('industry', 'ind_relative_volume_20', 13, true),
    ('industry', 'ind_relative_volatility_20', 14, true),
    ('industry', 'ind_relative_flow_20', 15, true),
    ('industry', 'ind_momentum_rank_20', 4, true),
    ('industry', 'ind_value_rank', 17, true),
    ('industry', 'ind_size_rank', 18, true),
    ('industry', 'ind_code_l1', 19, true),
    ('industry', 'ind_code_l2', 20, true),
    ('industry', 'ind_ret_5', 21, true),
    ('industry', 'ind_ret_10', 22, true),
    ('industry', 'ind_ret_20', 23, true),
    ('industry', 'ind_rotation_speed_20', 24, true),
    ('industry', 'ind_breadth_up_20', 25, true),
    ('industry', 'ind_volume_ratio_20', 26, true),
    ('industry', 'ind_crowding_20', 27, true),
    ('industry', 'ind_netflow_rank_20', 28, true),
    ('industry', 'ind_relative_pe', 29, true),
    ('industry', 'ind_concentration', 30, true),
    ('industry', 'ind_relative_momentum_20', 31, true),
    ('industry', 'ind_momentum_decay', 32, true),
    ('microstructure', 'micro_qsp_equal', 1, true),
    ('microstructure', 'micro_esp_equal', 2, true),
    ('microstructure', 'micro_aqsp_equal', 3, true),
    ('microstructure', 'micro_qsp_time', 4, true),
    ('microstructure', 'micro_esp_time', 5, true),
    ('microstructure', 'micro_qsp_volume', 6, true),
    ('microstructure', 'micro_esp_volume', 7, true),
    ('microstructure', 'micro_qsp_amount', 8, true),
    ('microstructure', 'micro_esp_amount', 9, true),
    ('microstructure', 'micro_effective_spread', 10, true),
    ('microstructure', 'micro_quoted_spread', 11, true),
    ('microstructure', 'micro_spread_vol_20', 12, true),
    ('microstructure', 'micro_imbalance_volume', 13, true),
    ('microstructure', 'micro_imbalance_amount', 14, true),
    ('microstructure', 'micro_imbalance_count', 15, true),
    ('microstructure', 'micro_imbalance_large', 16, true),
    ('microstructure', 'micro_imbalance_medium', 17, true),
    ('microstructure', 'micro_imbalance_small', 18, true),
    ('microstructure', 'micro_jump_flag', 19, true),
    ('microstructure', 'micro_pressure_score', 20, true),
    ('microstructure', 'micro_amihud_illiquidity', 21, true),
    ('microstructure', 'micro_kyle_lambda', 22, true),
    ('microstructure', 'micro_price_impact_large', 23, true),
    ('microstructure', 'micro_impact_cost', 24, true),
    ('microstructure', 'micro_impact_elasticity', 25, true),
    ('microstructure', 'micro_aqsp', 26, true),
    ('microstructure', 'micro_aesp', 27, true),
    ('microstructure', 'micro_qsp_vol_20', 28, true),
    ('microstructure', 'micro_esp_vol_20', 29, true),
    ('microstructure', 'micro_spread_slope_1_5', 30, true),
    ('microstructure', 'micro_bid_ask_vol_ratio', 31, true),
    ('microstructure', 'micro_depth_imbalance_1', 32, true),
    ('microstructure', 'micro_depth_imbalance_5', 33, true),
    ('microstructure', 'micro_depth_slope', 34, true),
    ('microstructure', 'micro_order_flow_toxicity', 35, true),
    ('microstructure', 'micro_informed_ratio', 36, true),
    ('microstructure', 'micro_jump_count_1pct', 37, true),
    ('microstructure', 'micro_open_gap', 38, true),
    ('microstructure', 'micro_trade_buy_pressure', 39, true),
    ('microstructure', 'micro_trade_sell_pressure', 40, true),
    ('microstructure', 'flow_cancel_buy_rate', 1058, true),
    ('microstructure', 'flow_cancel_cluster', 1059, true),
    ('microstructure', 'flow_cancel_depth_dist', 1060, true),
    ('microstructure', 'flow_cancel_hft_ratio', 1061, true),
    ('microstructure', 'flow_cancel_imbalance', 1062, true),
    ('microstructure', 'flow_cancel_lifetime', 1063, true),
    ('microstructure', 'flow_cancel_post_price_change', 1064, true),
    ('microstructure', 'flow_cancel_price_deviation', 1065, true),
    ('microstructure', 'flow_cancel_rate', 1066, true),
    ('microstructure', 'flow_cancel_sell_rate', 1067, true),
    ('microstructure', 'flow_cancel_spoof', 1068, true),
    ('microstructure', 'flow_imbalance_autocorr', 1069, true),
    ('microstructure', 'flow_imbalance_close', 1070, true),
    ('microstructure', 'flow_imbalance_mid_am', 1071, true),
    ('microstructure', 'flow_imbalance_mid_pm', 1072, true),
    ('microstructure', 'flow_imbalance_open', 1073, true),
    ('microstructure', 'flow_imbalance_revert_speed', 1074, true),
    ('microstructure', 'flow_large_pct', 1075, true),
    ('microstructure', 'flow_order_arrival_rate', 1076, true),
    ('microstructure', 'flow_order_book_rebuild', 1077, true),
    ('microstructure', 'flow_order_duration_p50', 1078, true),
    ('microstructure', 'flow_order_duration_p90', 1079, true),
    ('microstructure', 'flow_order_imbalance', 1080, true),
    ('microstructure', 'flow_order_large_ratio', 1081, true),
    ('microstructure', 'flow_order_quality', 1082, true),
    ('microstructure', 'flow_order_size_skew', 1083, true),
    ('microstructure', 'flow_order_type_diversity', 1084, true),
    ('microstructure', 'micro_adverse_selection', 1085, true),
    ('microstructure', 'micro_adverse_selection_cost', 1086, true),
    ('microstructure', 'micro_call_auction_depth_change', 1087, true),
    ('microstructure', 'micro_call_auction_vol_ratio', 1088, true),
    ('microstructure', 'micro_close_auction_impact', 1089, true),
    ('microstructure', 'micro_close_squeeze', 1090, true),
    ('microstructure', 'micro_depth_ask', 1091, true),
    ('microstructure', 'micro_depth_bid', 1092, true),
    ('microstructure', 'micro_depth_close', 1093, true),
    ('microstructure', 'micro_depth_concentration_ask', 1094, true),
    ('microstructure', 'micro_depth_concentration_bid', 1095, true),
    ('microstructure', 'micro_depth_effective', 1096, true),
    ('microstructure', 'micro_depth_extreme', 1097, true),
    ('microstructure', 'micro_depth_imbalance_10', 1098, true),
    ('microstructure', 'micro_depth_mid', 1099, true),
    ('microstructure', 'micro_depth_open', 1100, true),
    ('microstructure', 'micro_depth_ratio_1', 1101, true),
    ('microstructure', 'micro_depth_ratio_10', 1102, true),
    ('microstructure', 'micro_depth_ratio_5', 1103, true),
    ('microstructure', 'micro_depth_recovery', 1104, true),
    ('microstructure', 'micro_depth_volatility', 1105, true),
    ('microstructure', 'micro_depth_weighted_ask', 1106, true),
    ('microstructure', 'micro_depth_weighted_bid', 1107, true),
    ('microstructure', 'micro_impact_decay_half_life', 1108, true),
    ('microstructure', 'micro_impact_permanent_ratio', 1109, true),
    ('microstructure', 'micro_information_share', 1110, true),
    ('microstructure', 'micro_jump_cluster', 1111, true),
    ('microstructure', 'micro_jump_count_05pct', 1112, true),
    ('microstructure', 'micro_jump_recovery_time', 1113, true),
    ('microstructure', 'micro_jump_size_max', 1114, true),
    ('microstructure', 'micro_jump_size_mean', 1115, true),
    ('microstructure', 'micro_jump_skew', 1116, true),
    ('microstructure', 'micro_liquidity_amihud_20', 1117, true),
    ('microstructure', 'micro_liquidity_amihud_5', 1118, true),
    ('microstructure', 'micro_liquidity_close', 1119, true),
    ('microstructure', 'micro_liquidity_concentration', 1120, true),
    ('microstructure', 'micro_liquidity_cost', 1121, true),
    ('microstructure', 'micro_liquidity_daily_pattern', 1122, true),
    ('microstructure', 'micro_liquidity_extreme', 1123, true),
    ('microstructure', 'micro_liquidity_holden', 1124, true),
    ('microstructure', 'micro_liquidity_mining', 1125, true),
    ('microstructure', 'micro_liquidity_ratio', 1126, true),
    ('microstructure', 'micro_liquidity_relative_spread', 1127, true),
    ('microstructure', 'micro_liquidity_roll', 1128, true),
    ('microstructure', 'micro_liquidity_turnover_decay', 1129, true),
    ('microstructure', 'micro_liquidity_twa', 1130, true),
    ('microstructure', 'micro_liquidity_volatility', 1131, true),
    ('microstructure', 'micro_liquidity_volume_depth_ratio', 1132, true),
    ('microstructure', 'micro_lunch_break_gap', 1133, true),
    ('microstructure', 'micro_order_imbalance_tox', 1134, true),
    ('microstructure', 'micro_price_discovery', 1135, true),
    ('microstructure', 'micro_realized_spread', 1136, true),
    ('microstructure', 'micro_spread_U_shape', 1137, true),
    ('microstructure', 'micro_spread_close', 1138, true),
    ('microstructure', 'micro_spread_decomposition', 1139, true),
    ('microstructure', 'micro_spread_mid', 1140, true),
    ('microstructure', 'micro_spread_open', 1141, true),
    ('microstructure', 'micro_spread_recovery', 1142, true),
    ('microstructure', 'micro_spread_slope_1_10', 1143, true),
    ('microstructure', 'micro_spread_slope_5_10', 1144, true),
    ('microstructure', 'micro_spread_vol_ratio', 1145, true),
    ('microstructure', 'micro_toxicity_asymmetry', 1146, true),
    ('microstructure', 'micro_toxicity_persistence', 1147, true),
    ('microstructure', 'micro_trade_arrival_rate', 1148, true),
    ('microstructure', 'micro_trade_continuation', 1149, true),
    ('microstructure', 'micro_trade_interval_cv', 1150, true),
    ('microstructure', 'micro_trade_interval_mean', 1151, true),
    ('microstructure', 'micro_trade_interval_median', 1152, true),
    ('microstructure', 'micro_trade_run_length', 1153, true),
    ('microstructure', 'micro_trade_seq_entropy', 1154, true),
    ('microstructure', 'micro_trade_sign_autocorr', 1155, true),
    ('microstructure', 'micro_trade_sign_transition_BB', 1156, true),
    ('microstructure', 'micro_trade_sign_transition_EB', 1157, true),
    ('microstructure', 'micro_trade_zero_interval_ratio', 1158, true),
    ('microstructure', 'micro_volume_sync', 1159, true),
    ('microstructure', 'micro_vpin_100', 1160, true),
    ('microstructure', 'micro_vpin_amount_ratio', 1161, true),
    ('microstructure', 'micro_vpin_bayesian', 1162, true),
    ('microstructure', 'micro_vpin_conviction', 1163, true),
    ('microstructure', 'micro_vpin_entropy', 1164, true),
    ('microstructure', 'micro_vpin_hurst', 1165, true),
    ('microstructure', 'micro_vpin_kyle', 1166, true),
    ('microstructure', 'micro_vpin_quantile_ratio', 1167, true),
    ('microstructure', 'micro_vpin_surge', 1168, true),
    ('microstructure', 'micro_vpin_tail_risk', 1169, true),
    ('microstructure', 'micro_vpin_trend', 1170, true),
    ('microstructure', 'micro_vpin_vol_ratio', 1171, true),
    ('microstructure', 'micro_vpin_zscore_20', 1172, true),
    ('microstructure', 'micro_zone_distribution', 1173, true),
    ('microstructure', 'micro_zone_imbalance_am', 1174, true),
    ('microstructure', 'micro_zone_imbalance_pm', 1175, true),
    ('microstructure', 'micro_zone_morning_evening_ratio', 1176, true),
    ('microstructure', 'micro_zone_rv_ratio_AM', 1177, true),
    ('microstructure', 'micro_zone_rv_ratio_PM', 1178, true),
    ('microstructure', 'micro_zone_rv_ratio_close', 1179, true),
    ('microstructure', 'micro_zone_rv_ratio_open', 1180, true),
    ('microstructure', 'micro_zone_spread_ratio_close', 1181, true),
    ('microstructure', 'micro_zone_spread_ratio_mid', 1182, true),
    ('microstructure', 'micro_zone_spread_ratio_open', 1183, true),
    ('microstructure', 'micro_zone_vol_ratio_T1', 1184, true),
    ('microstructure', 'micro_zone_vol_ratio_T2', 1185, true),
    ('microstructure', 'micro_zone_vol_ratio_T3', 1186, true),
    ('microstructure', 'micro_zone_vol_ratio_T4', 1187, true),
    ('microstructure', 'micro_zone_vol_ratio_T5', 1188, true),
    ('microstructure', 'micro_zone_vol_ratio_T6', 1189, true),
    ('microstructure', 'micro_zone_vol_ratio_T7', 1190, true),
    ('microstructure', 'micro_zone_vol_ratio_T8', 1191, true),
    ('microstructure', 'micro_zone_vpin_open', 1192, true),
    ('gtja', 'gtja_016', 1, true),
    ('gtja', 'gtja_032', 2, true),
    ('gtja', 'gtja_062', 3, true),
    ('gtja', 'gtja_083', 4, true),
    ('gtja', 'gtja_090', 5, true),
    ('gtja', 'gtja_099', 6, true),
    ('gtja', 'gtja_036', 7, true),
    ('gtja', 'gtja_070', 8, true),
    ('gtja', 'gtja_074', 9, true),
    ('gtja', 'gtja_150', 10, true),
    ('gtja', 'gtja_176', 11, true),
    ('gtja', 'gtja_179', 12, true),
    ('gtja', 'gtja_042', 13, true),
    ('gtja', 'gtja_095', 14, true),
    ('gtja', 'gtja_158', 15, true),
    ('gtja', 'gtja_159', 16, true),
    ('chip', 'chip_profit_ratio_20', 1, true),
    ('chip', 'chip_profit_ratio_60', 2, true),
    ('chip', 'chip_profit_ratio_120', 3, true),
    ('chip', 'chip_concentration_20', 4, true),
    ('chip', 'chip_peak_distance', 5, true),
    ('chip', 'chip_floating_ratio', 6, true),
    ('chip', 'chip_cost_90_width', 7, true),
    ('chip', 'chip_profit_delta_5', 8, true),
    ('concept', 'concept_hot_score', 1, true),
    ('concept', 'concept_momentum_top3', 2, true),
    ('concept', 'concept_exposure_top1', 3, true),
    ('concept', 'concept_rotation_score', 4, true),
    ('concept', 'concept_crowding_max', 5, true),
    ('concept', 'concept_diversity', 6, true),
    ('concept', 'concept_flow_rank', 7, true),
    ('concept', 'concept_leader_score', 8, true),
    ('concept', 'concept_cross_sector', 9, true),
    ('concept', 'concept_volume_ratio', 10, true),
    ('technical', 'tech_bb_width', 1, true),
    ('technical', 'tech_bb_pos', 2, true),
    ('technical', 'tech_cci_20', 3, true),
    ('technical', 'tech_adx_14', 4, true),
    ('technical', 'tech_vol_price_corr_20', 5, true),
    ('technical', 'rsi_6', 1, true),
    ('technical', 'macd_hist', 2, true),
    ('technical', 'kdj_d', 3, true),
    ('technical', 'amount', 1193, true),
    ('technical', 'kdj_j', 1194, true),
    ('technical', 'kdj_k', 1195, true),
    ('technical', 'ma10', 1196, true),
    ('technical', 'ma20', 1197, true),
    ('technical', 'ma5', 1198, true),
    ('technical', 'ma60', 1199, true),
    ('technical', 'ma_gap_10', 1200, true),
    ('technical', 'ma_gap_20', 1201, true),
    ('technical', 'ma_gap_5', 1202, true),
    ('technical', 'macd_dea', 1203, true),
    ('technical', 'macd_dif', 1204, true),
    ('technical', 'mfi_14', 1205, true),
    ('technical', 'obv_slope_20', 1206, true),
    ('technical', 'pct_change', 1207, true),
    ('technical', 'rsi_14', 1208, true),
    ('technical', 'tech_close_to_high_20', 1209, true),
    ('technical', 'tech_max_drawdown_20', 1210, true),
    ('technical', 'vol_weighted_price', 1211, true),
    ('fundamental', 'fun_turnover_1', 1, true),
    ('fundamental', 'fun_turnover_5', 2, true),
    ('fundamental', 'fun_turnover_20', 3, true),
    ('fundamental', 'fun_mv', 4, true),
    ('fundamental', 'fun_total_mv', 5, true),
    ('fundamental', 'fun_pe', 6, true),
    ('fundamental', 'fun_pb', 7, true),
    ('fundamental', 'fun_bp', 8, true),
    ('fundamental', 'fun_ep', 9, true),
    ('fundamental', 'fun_mv_rank', 10, true),
    ('fundamental', 'fun_value_zscore', 11, true),
    ('fundamental', 'fun_roe', 12, true),
    ('fundamental', 'fun_peg', 13, true),
    ('fundamental', 'dividend_rate', 10, true),
    ('fundamental', 'ps_ttm', 14, true),
    ('fundamental', 'annual_net_profit', 1212, true),
    ('fundamental', 'circulating_capital', 1213, true),
    ('fundamental', 'equity', 1214, true),
    ('fundamental', 'float_mv', 1215, true),
    ('fundamental', 'fun_float_mv', 1216, true),
    ('fundamental', 'fun_np_growth', 1217, true),
    ('fundamental', 'net_profit_ttm', 1218, true),
    ('fundamental', 'pb', 1219, true),
    ('fundamental', 'pe_static', 1220, true),
    ('fundamental', 'pe_ttm', 1221, true),
    ('fundamental', 'revenue_ttm', 1222, true),
    ('fundamental', 'total_capital', 1223, true),
    ('fundamental', 'total_mv', 1224, true),
    ('holding', 'ca_n_pis', 1, true),
    ('holding', 'ca_hhi_disc', 2, true),
    ('holding', 'ca_rank_overlap_20d', 3, true),
    ('holding', 'ca_broker_pct', 4, true),
    ('holding', 'ca_disclosed_sum', 5, true),
    ('holding', 'ca_cust_share_disc', 6, true),
    ('holding', 'ca_south_pct', 7, true),
    ('holding', 'sb_quantity', 8, true),
    ('custom', 'custom_ret_1d', 1, true),
    ('custom', 'custom_amp_1d', 2, true),
    ('custom', 'custom_close_pos', 3, true),
    ('custom', 'custom_vol_ratio_5', 4, true),
    ('custom', 'custom_amt_ma_5', 5, true)
) AS v(category_id, feature_key, order_no, enabled)
WHERE EXISTS (SELECT 1 FROM qm_feature_set_version WHERE version_id = 'v2.0')
ON CONFLICT (version_id, feature_key) DO NOTHING;

COMMIT;
